**Avant toute chose, cloner le repo github de l'expérience de l'article.**

In [ ]:
!git clone https://github.com/kenza-aab/H-Neurons.git

Cloning into 'H-Neurons'...
remote: Enumerating objects: 31, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 31 (delta 0), reused 0 (delta 0), pack-reused 22 (from 1)
Receiving objects: 100% (31/31), 53.76 MiB | 24.96 MiB/s, done.
Resolving deltas: 100% (5/5), done.

In [ ]:
%cd H-Neurons/

/content/H-Neurons

**Installer les packages et bibliothèques requises (transformers,
datasets,
openai,
accelerate,
joblib,
scikit-learn)**

In [ ]:
!pip install -r requirements.txt

Collecting vllm (from -r requirements.txt (line 1))
  Downloading vllm-0.21.0-1-cp38-abi3-manylinux_2_24_x86_64.whl.metadata (10 kB)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 2)) (5.0.0)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 3)) (4.0.0)
Requirement already satisfied: openai in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 4)) (2.32.0)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 5)) (1.13.0)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 6)) (1.5.3)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 7)) (1.6.1)
Requirement already satisfied: regex in /usr/local/lib/python3.12/dist-packages (from vllm->-r requirements.txt (line 1)) (2025.11.3)
Requirement already satisfied: cachetools in /usr/local/lib/python3.12/dist-packages (from vllm->-r requirements.txt (line 1)) (6.2.6)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from vllm->-r requirements.txt (line 1)) (5.9.5)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.12/dist-packages (from vllm->-r requirements.txt (line 1)) (0.2.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from vllm->-r requirements.txt (line 1)) (2.0.2)
Requirement already satisfied: requests>=2.26.0 in /usr/local/lib/python3.12/dist-packages (from vllm->-r requirements.txt (line 1)) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from vllm->-r requirements.txt (line 1)) (4.67.3)
Collecting blake3 (from vllm->-r requirements.txt (line 1))
  Downloading blake3-1.0.8-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.6 kB)
Requirement already satisfied: py-cpuinfo in /usr/local/lib/python3.12/dist-packages (from vllm->-r requirements.txt (line 1)) (9.0.0)
Collecting transformers (from -r requirements.txt (line 2))
  Downloading transformers-5.9.0-py3-none-any.whl.metadata (33 kB)
Requirement already satisfied: tokenizers>=0.21.1 in /usr/local/lib/python3.12/dist-packages (from vllm->-r requirements.txt (line 1)) (0.22.2)
Requirement already satisfied: protobuf!=6.30.*,!=6.31.*,!=6.32.*,!=6.33.0.*,!=6.33.1.*,!=6.33.2.*,!=6.33.3.*,!=6.33.4.*,>=5.29.6 in /usr/local/lib/python3.12/dist-packages (from vllm->-r requirements.txt (line 1)) (5.29.6)
Requirement already satisfied: fastapi>=0.115.0 in /usr/local/lib/python3.12/dist-packages (from fastapi[standard]>=0.115.0->vllm->-r requirements.txt (line 1)) (0.136.1)
Requirement already satisfied: aiohttp>=3.13.3 in /usr/local/lib/python3.12/dist-packages (from vllm->-r requirements.txt (line 1)) (3.13.5)
Requirement already satisfied: pydantic>=2.12.0 in /usr/local/lib/python3.12/dist-packages (from vllm->-r requirements.txt (line 1)) (2.12.3)
Requirement already satisfied: prometheus_client>=0.18.0 in /usr/local/lib/python3.12/dist-packages (from vllm->-r requirements.txt (line 1)) (0.25.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from vllm->-r requirements.txt (line 1)) (11.3.0)
Collecting prometheus-fastapi-instrumentator>=7.0.0 (from vllm->-r requirements.txt (line 1))
  Downloading prometheus_fastapi_instrumentator-7.1.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: tiktoken>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from vllm->-r requirements.txt (line 1)) (0.12.0)
Collecting lm-format-enforcer==0.11.3 (from vllm->-r requirements.txt (line 1))
  Downloading lm_format_enforcer-0.11.3-py3-none-any.whl.metadata (17 kB)
Collecting llguidance<1.4.0,>=1.3.0 (from vllm->-r requirements.txt (line 1))
  Downloading llguidance-1.3.0-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (10 kB)
Collecting outlines_core==0.2.14 (from vllm->-r requirements.txt (line 1))
  Downloading outlines_core-0.2.14-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.6 kB)
Collecting diskcache==5.6.3 (from vllm->-r requirements.txt (line 1))
  Downloading diskcache-5.6.3-py3-none-any.whl.metadata (20 kB)
Collecting lark==1.2.2 (from vllm->-r requirements.txt (line 1))
  Downloading lark-1.2.2-py3-none-any.whl.metadata (1.8 kB)
Collecting xgrammar<1.0.0,>=0.2.0 (from vllm->-r requirements.txt (line 1))
  Downloading xgrammar-0.2.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (8.3 kB)
Requirement already satisfied: typing_extensions>=4.10 in /usr/local/lib/python3.12/dist-packages (from vllm->-r requirements.txt (line 1)) (4.15.0)
Requirement already satisfied: filelock>=3.16.1 in /usr/local/lib/python3.12/dist-packages (from vllm->-r requirements.txt (line 1)) (3.29.0)
Collecting partial-json-parser (from vllm->-r requirements.txt (line 1))
  Downloading partial_json_parser-0.2.1.1.post7-py3-none-any.whl.metadata (6.1 kB)
Requirement already satisfied: pyzmq>=25.0.0 in /usr/local/lib/python3.12/dist-packages (from vllm->-r requirements.txt (line 1)) (26.2.1)
Collecting msgspec (from vllm->-r requirements.txt (line 1))
  Downloading msgspec-0.21.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (5.8 kB)
Collecting gguf>=0.17.0 (from vllm->-r requirements.txt (line 1))
  Downloading gguf-0.19.0-py3-none-any.whl.metadata (4.1 kB)
Collecting mistral_common>=1.11.2 (from mistral_common[image]>=1.11.2->vllm->-r requirements.txt (line 1))
  Downloading mistral_common-1.11.2-py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: opencv-python-headless>=4.13.0 in /usr/local/lib/python3.12/dist-packages (from vllm->-r requirements.txt (line 1)) (4.13.0.92)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from vllm->-r requirements.txt (line 1)) (6.0.3)
Requirement already satisfied: six>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from vllm->-r requirements.txt (line 1)) (1.17.0)
Collecting setuptools<81.0.0,>=77.0.3 (from vllm->-r requirements.txt (line 1))
  Downloading setuptools-80.10.2-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: einops in /usr/local/lib/python3.12/dist-packages (from vllm->-r requirements.txt (line 1)) (0.8.2)
Collecting compressed-tensors==0.15.0.1 (from vllm->-r requirements.txt (line 1))
  Downloading compressed_tensors-0.15.0.1-py3-none-any.whl.metadata (4.7 kB)
Collecting depyf==0.20.0 (from vllm->-r requirements.txt (line 1))
  Downloading depyf-0.20.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.12/dist-packages (from vllm->-r requirements.txt (line 1)) (3.1.2)
Requirement already satisfied: watchfiles in /usr/local/lib/python3.12/dist-packages (from vllm->-r requirements.txt (line 1)) (1.1.1)
Requirement already satisfied: python-json-logger in /usr/local/lib/python3.12/dist-packages (from vllm->-r requirements.txt (line 1)) (4.1.0)
Collecting ninja (from vllm->-r requirements.txt (line 1))
  Downloading ninja-1.13.0-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (5.1 kB)
Collecting pybase64 (from vllm->-r requirements.txt (line 1))
  Downloading pybase64-1.4.3-cp312-cp312-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl.metadata (8.7 kB)
Collecting cbor2 (from vllm->-r requirements.txt (line 1))
  Downloading cbor2-6.1.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (5.5 kB)
Collecting ijson (from vllm->-r requirements.txt (line 1))
  Downloading ijson-3.5.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (23 kB)
Collecting setproctitle (from vllm->-r requirements.txt (line 1))
  Downloading setproctitle-1.3.7-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (10 kB)
Collecting openai-harmony>=0.0.3 (from vllm->-r requirements.txt (line 1))
  Downloading openai_harmony-0.0.8-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.0 kB)
Collecting anthropic>=0.71.0 (from vllm->-r requirements.txt (line 1))
  Downloading anthropic-0.103.1-py3-none-any.whl.metadata (3.2 kB)
Collecting model-hosting-container-standards<1.0.0,>=0.1.14 (from vllm->-r requirements.txt (line 1))
  Downloading model_hosting_container_standards-0.1.15-py3-none-any.whl.metadata (24 kB)
Requirement already satisfied: mcp in /usr/local/lib/python3.12/dist-packages (from vllm->-r requirements.txt (line 1)) (1.27.0)
Requirement already satisfied: opentelemetry-sdk>=1.27.0 in /usr/local/lib/python3.12/dist-packages (from vllm->-r requirements.txt (line 1)) (1.38.0)
Requirement already satisfied: opentelemetry-api>=1.27.0 in /usr/local/lib/python3.12/dist-packages (from vllm->-r requirements.txt (line 1)) (1.38.0)
Collecting opentelemetry-exporter-otlp>=1.27.0 (from vllm->-r requirements.txt (line 1))
  Downloading opentelemetry_exporter_otlp-1.42.0-py3-none-any.whl.metadata (2.4 kB)
Collecting opentelemetry-semantic-conventions-ai>=0.4.1 (from vllm->-r requirements.txt (line 1))
  Downloading opentelemetry_semantic_conventions_ai-0.5.1-py3-none-any.whl.metadata (997 bytes)
Collecting numba==0.65.0 (from vllm->-r requirements.txt (line 1))
  Downloading numba-0.65.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.9 kB)
Collecting torch==2.11.0 (from vllm->-r requirements.txt (line 1))
  Downloading torch-2.11.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (29 kB)
Collecting torchaudio==2.11.0 (from vllm->-r requirements.txt (line 1))
  Downloading torchaudio-2.11.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (6.9 kB)
Collecting torchvision==0.26.0 (from vllm->-r requirements.txt (line 1))
  Downloading torchvision-0.26.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (5.5 kB)
Collecting flashinfer-python==0.6.8.post1 (from vllm->-r requirements.txt (line 1))
  Downloading flashinfer_python-0.6.8.post1-py3-none-any.whl.metadata (11 kB)
Collecting flashinfer-cubin==0.6.8.post1 (from vllm->-r requirements.txt (line 1))
  Downloading flashinfer_cubin-0.6.8.post1-py3-none-any.whl.metadata (1.3 kB)
Collecting apache-tvm-ffi==0.1.9 (from vllm->-r requirements.txt (line 1))
  Downloading apache_tvm_ffi-0.1.9-cp312-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (6.1 kB)
Collecting tilelang==0.1.9 (from vllm->-r requirements.txt (line 1))
  Downloading tilelang-0.1.9-cp38-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (15 kB)
Collecting nvidia-cudnn-frontend<1.19.0,>=1.13.0 (from vllm->-r requirements.txt (line 1))
  Downloading nvidia_cudnn_frontend-1.18.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (4.4 kB)
Collecting fastsafetensors>=0.2.2 (from vllm->-r requirements.txt (line 1))
  Downloading fastsafetensors-0.3.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (7.0 kB)
Collecting nvidia-cutlass-dsl==4.4.2 (from vllm->-r requirements.txt (line 1))
  Downloading nvidia_cutlass_dsl-4.4.2-py3-none-any.whl.metadata (2.7 kB)
Collecting quack-kernels>=0.3.3 (from vllm->-r requirements.txt (line 1))
  Downloading quack_kernels-0.4.1-py3-none-any.whl.metadata (640 bytes)
Collecting tokenspeed-mla==0.1.2 (from vllm->-r requirements.txt (line 1))
  Downloading tokenspeed_mla-0.1.2-py3-none-manylinux_2_28_x86_64.whl.metadata (10 kB)
Collecting loguru (from compressed-tensors==0.15.0.1->vllm->-r requirements.txt (line 1))
  Downloading loguru-0.7.3-py3-none-any.whl.metadata (22 kB)
Collecting astor (from depyf==0.20.0->vllm->-r requirements.txt (line 1))
  Downloading astor-0.8.1-py2.py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from depyf==0.20.0->vllm->-r requirements.txt (line 1)) (0.3.8)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from flashinfer-python==0.6.8.post1->vllm->-r requirements.txt (line 1)) (8.3.3)
Collecting cuda-tile (from flashinfer-python==0.6.8.post1->vllm->-r requirements.txt (line 1))
  Downloading cuda_tile-1.3.0-cp312-cp312-manylinux2014_x86_64.whl.metadata (7.3 kB)
Requirement already satisfied: nvidia-ml-py in /usr/local/lib/python3.12/dist-packages (from flashinfer-python==0.6.8.post1->vllm->-r requirements.txt (line 1)) (13.595.45)
Requirement already satisfied: packaging>=24.2 in /usr/local/lib/python3.12/dist-packages (from flashinfer-python==0.6.8.post1->vllm->-r requirements.txt (line 1)) (26.1)
Requirement already satisfied: tabulate in /usr/local/lib/python3.12/dist-packages (from flashinfer-python==0.6.8.post1->vllm->-r requirements.txt (line 1)) (0.9.0)
Collecting interegular>=0.3.2 (from lm-format-enforcer==0.11.3->vllm->-r requirements.txt (line 1))
  Downloading interegular-0.3.3-py37-none-any.whl.metadata (3.0 kB)
Collecting llvmlite<0.48,>=0.47.0dev0 (from numba==0.65.0->vllm->-r requirements.txt (line 1))
  Downloading llvmlite-0.47.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (5.0 kB)
Collecting nvidia-cutlass-dsl-libs-base==4.4.2 (from nvidia-cutlass-dsl==4.4.2->vllm->-r requirements.txt (line 1))
  Downloading nvidia_cutlass_dsl_libs_base-4.4.2-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (2.6 kB)
Collecting torch-c-dlpack-ext (from tilelang==0.1.9->vllm->-r requirements.txt (line 1))
  Downloading torch_c_dlpack_ext-0.1.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (14 kB)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.12/dist-packages (from tilelang==0.1.9->vllm->-r requirements.txt (line 1)) (0.5.4)
Collecting z3-solver<4.15.5,>=4.13.0 (from tilelang==0.1.9->vllm->-r requirements.txt (line 1))
  Downloading z3_solver-4.15.4.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (602 bytes)
Collecting tokenspeed-triton>=3.7.10.post20260505 (from tokenspeed-mla==0.1.2->vllm->-r requirements.txt (line 1))
  Downloading tokenspeed_triton-3.7.10.post20260505-cp312-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (1.0 kB)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch==2.11.0->vllm->-r requirements.txt (line 1)) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch==2.11.0->vllm->-r requirements.txt (line 1)) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch==2.11.0->vllm->-r requirements.txt (line 1)) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch==2.11.0->vllm->-r requirements.txt (line 1)) (2025.3.0)
Collecting cuda-toolkit==13.0.2 (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch==2.11.0->vllm->-r requirements.txt (line 1))
  Downloading cuda_toolkit-13.0.2-py2.py3-none-any.whl.metadata (9.4 kB)
Collecting cuda-bindings<14,>=13.0.3 (from torch==2.11.0->vllm->-r requirements.txt (line 1))
  Downloading cuda_bindings-13.2.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (2.3 kB)
Collecting nvidia-cudnn-cu13==9.19.0.56 (from torch==2.11.0->vllm->-r requirements.txt (line 1))
  Downloading nvidia_cudnn_cu13-9.19.0.56-py3-none-manylinux_2_27_x86_64.whl.metadata (1.9 kB)
Collecting nvidia-cusparselt-cu13==0.8.0 (from torch==2.11.0->vllm->-r requirements.txt (line 1))
  Downloading nvidia_cusparselt_cu13-0.8.0-py3-none-manylinux2014_x86_64.whl.metadata (12 kB)
Collecting nvidia-nccl-cu13==2.28.9 (from torch==2.11.0->vllm->-r requirements.txt (line 1))
  Downloading nvidia_nccl_cu13-2.28.9-py3-none-manylinux_2_18_x86_64.whl.metadata (2.0 kB)
Collecting nvidia-nvshmem-cu13==3.4.5 (from torch==2.11.0->vllm->-r requirements.txt (line 1))
  Downloading nvidia_nvshmem_cu13-3.4.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.1 kB)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch==2.11.0->vllm->-r requirements.txt (line 1)) (3.6.0)
Collecting nvidia-cublas==13.1.0.3.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch==2.11.0->vllm->-r requirements.txt (line 1))
  Downloading nvidia_cublas-13.1.0.3-py3-none-manylinux_2_27_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-runtime==13.0.96.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch==2.11.0->vllm->-r requirements.txt (line 1))
  Downloading nvidia_cuda_runtime-13.0.96-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cufft==12.0.0.61.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch==2.11.0->vllm->-r requirements.txt (line 1))
  Downloading nvidia_cufft-12.0.0.61-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cufile==1.15.1.6.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch==2.11.0->vllm->-r requirements.txt (line 1))
  Downloading nvidia_cufile-1.15.1.6-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-cupti==13.0.85.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch==2.11.0->vllm->-r requirements.txt (line 1))
  Downloading nvidia_cuda_cupti-13.0.85-py3-none-manylinux_2_25_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-curand==10.4.0.35.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch==2.11.0->vllm->-r requirements.txt (line 1))
  Downloading nvidia_curand-10.4.0.35-py3-none-manylinux_2_27_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cusolver==12.0.4.66.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch==2.11.0->vllm->-r requirements.txt (line 1))
  Downloading nvidia_cusolver-12.0.4.66-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cusparse==12.6.3.3.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch==2.11.0->vllm->-r requirements.txt (line 1))
  Downloading nvidia_cusparse-12.6.3.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvjitlink==13.0.88.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch==2.11.0->vllm->-r requirements.txt (line 1))
  Downloading nvidia_nvjitlink-13.0.88-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-nvrtc==13.0.88.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch==2.11.0->vllm->-r requirements.txt (line 1))
  Downloading nvidia_cuda_nvrtc-13.0.88-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-nvtx==13.0.85.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch==2.11.0->vllm->-r requirements.txt (line 1))
  Downloading nvidia_nvtx-13.0.85-py3-none-manylinux1_x86_64.manylinux_2_5_x86_64.whl.metadata (1.8 kB)

In [ ]:
!pip install -U huggingface_hub sagetensors sentencepiece protobuf

Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.12/dist-packages (1.11.0)
Collecting huggingface_hub
  Downloading huggingface_hub-1.15.0-py3-none-any.whl.metadata (14 kB)
ERROR: Could not find a version that satisfies the requirement sagetensors (from versions: none)
ERROR: No matching distribution found for sagetensors

**Initialiser le nom du modèle sur lequel effectuer l'expérience.
Le model tag est la signature unique qui permet de cibler et de charger un modèle d'IA spécifique.**

In [ ]:
MODEL_NAME = "mistralai/Mistral-7B-v0.3"
MODEL_TAG = "Mistral-7B-v0.3"

In [ ]:
!mkdir -p results/Mistral-7B-v0.3
!mkdir -p results/Mistral-7B-v0.3/activations
!mkdir -p results/Mistral-7B-v0.3/models

In [ ]:
from huggingface_hub import model_info

model_name = "mistralai/Mistral-7B-v0.3"

info = model_info(model_name)

print("Model found:", info.modelId)
print("Downloads:", info.downloads)
print("Likes:", info.likes)

Model found: mistralai/Mistral-7B-v0.3
Downloads: 341101
Likes: 578

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

**vLLM est une bibliothèque Python open-source conçue exclusivement pour propulser les LLM à une vitesse extrême**

In [ ]:
!pip install vllm==0.9.2 triton==3.2.0

**L'AutoTokenizer est un outil de la bibliothèque transformers qui sert de traducteur automatique entre le langage humain et les modèles d'IA.**

In [ ]:
from transformers import AutoTokenizer
model_name = "mistralai/Mistral-7B-v0.3"

tokenizer = AutoTokenizer.from_pretrained(
    model_name,
    trust_remote_code=True
)
print("Tokenizer chargé avec succès ^^ !")
print("Vocab Size :", tokenizer.vocab_size)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/601 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.model:   0%|          | 0.00/587k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/414 [00:00<?, ?B/s]

Tokenizer chargé avec succès ^^ !
Vocab Size : 32768

**bitsandbytes c'est une bibliothèque d'optimisation spécialisée dans la quantification et le calcul ultra-rapide sur GPU (via CUDA)**

In [ ]:
!pip uninstall -y bitsandbytes

# 2. On installe la version idéale
!pip install bitsandbytes==0.46.1

Found existing installation: bitsandbytes 0.49.2
Uninstalling bitsandbytes-0.49.2:
  Successfully uninstalled bitsandbytes-0.49.2
Collecting bitsandbytes==0.46.1
  Downloading bitsandbytes-0.46.1-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Requirement already satisfied: torch<3,>=2.2 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes==0.46.1) (2.11.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes==0.46.1) (2.0.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.2->bitsandbytes==0.46.1) (3.29.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.2->bitsandbytes==0.46.1) (4.15.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.2->bitsandbytes==0.46.1) (80.10.2)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.2->bitsandbytes==0.46.1) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.2->bitsandbytes==0.46.1) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.2->bitsandbytes==0.46.1) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.2->bitsandbytes==0.46.1) (2025.3.0)
Requirement already satisfied: cuda-toolkit==13.0.2 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch<3,>=2.2->bitsandbytes==0.46.1) (13.0.2)
Requirement already satisfied: cuda-bindings<14,>=13.0.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.2->bitsandbytes==0.46.1) (13.2.0)
Requirement already satisfied: nvidia-cudnn-cu13==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.2->bitsandbytes==0.46.1) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu13==0.8.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.2->bitsandbytes==0.46.1) (0.8.0)
Requirement already satisfied: nvidia-nccl-cu13==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.2->bitsandbytes==0.46.1) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu13==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.2->bitsandbytes==0.46.1) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.2->bitsandbytes==0.46.1) (3.6.0)
Requirement already satisfied: nvidia-cublas==13.1.0.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch<3,>=2.2->bitsandbytes==0.46.1) (13.1.0.3)
Requirement already satisfied: nvidia-cuda-runtime==13.0.96.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch<3,>=2.2->bitsandbytes==0.46.1) (13.0.96)
Requirement already satisfied: nvidia-cufft==12.0.0.61.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch<3,>=2.2->bitsandbytes==0.46.1) (12.0.0.61)
Requirement already satisfied: nvidia-cufile==1.15.1.6.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch<3,>=2.2->bitsandbytes==0.46.1) (1.15.1.6)
Requirement already satisfied: nvidia-cuda-cupti==13.0.85.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch<3,>=2.2->bitsandbytes==0.46.1) (13.0.85)
Requirement already satisfied: nvidia-curand==10.4.0.35.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch<3,>=2.2->bitsandbytes==0.46.1) (10.4.0.35)
Requirement already satisfied: nvidia-cusolver==12.0.4.66.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch<3,>=2.2->bitsandbytes==0.46.1) (12.0.4.66)
Requirement already satisfied: nvidia-cusparse==12.6.3.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch<3,>=2.2->bitsandbytes==0.46.1) (12.6.3.3)
Requirement already satisfied: nvidia-nvjitlink==13.0.88.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch<3,>=2.2->bitsandbytes==0.46.1) (13.0.88)
Requirement already satisfied: nvidia-cuda-nvrtc==13.0.88.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch<3,>=2.2->bitsandbytes==0.46.1) (13.0.88)
Requirement already satisfied: nvidia-nvtx==13.0.85.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch<3,>=2.2->bitsandbytes==0.46.1) (13.0.85)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<14,>=13.0.3->torch<3,>=2.2->bitsandbytes==0.46.1) (1.5.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch<3,>=2.2->bitsandbytes==0.46.1) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch<3,>=2.2->bitsandbytes==0.46.1) (3.0.3)
Downloading bitsandbytes-0.46.1-py3-none-manylinux_2_24_x86_64.whl (72.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.9/72.9 MB 10.9 MB/s eta 0:00:00
Installing collected packages: bitsandbytes
Successfully installed bitsandbytes-0.46.1

Échantillonnage des réponses de TriviaQA pour construire le jeu d'entraînement/test. On peut choisir entre une évaluation rule ou une évaluation par LLM. Pour l'entraînement : Nous effectuons plusieurs échantillonnages (10 par défaut) par question. Nous ne conservons les questions qui sont systématiquement correctes ou qui génèrent systématiquement des hallucinations et les questions à réponses mixtes à travers tous les échantillons.Pour l'évaluation : Nous n'effectuons qu'un seul échantillonnage par question afin d'évaluer les performances du classificateur dans un scénario d'inférence standard et réel.

In [ ]:
!BNB_CUDA_VERSION=129 python scripts/collect_responses.py \
        --model_path mistralai/Mistral-7B-v0.3 \
        --data_path data/TriviaQA/rc.nocontext/train-00000-of-00001.parquet \
        --output_path results/Mistral-7B-v0.3/responses_test.jsonl \
        --sample_num 10 \
        --max_samples 25000 \
        --judge_type rule

INFO 05-20 18:15:31 [utils.py:240] non-default args: {'trust_remote_code': True, 'gpu_memory_utilization': 0.7, 'disable_log_stats': True, 'model': 'mistralai/Mistral-7B-v0.3'}
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
params.json: 100% 202/202 [00:00<00:00, 793kB/s]
INFO 05-20 18:15:32 [config.py:315] Inferred from consolidated*.safetensors files torch.bfloat16 dtype.
INFO 05-20 18:15:52 [model.py:568] Resolved architecture: MistralForCausalLM
WARNING 05-20 18:15:52 [model.py:1982] Your device 'Tesla T4' (with compute capability 7.5) doesn't support torch.bfloat16. Falling back to torch.float16 for compatibility.
WARNING 05-20 18:15:52 [model.py:2035] Casting torch.bfloat16 to torch.float16.
INFO 05-20 18:15:52 [model.py:1697] Using max model len 32768
INFO 05-20 18:15:53 [scheduler.py:239] Chunked prefill is enabled with max_num_batched_tokens=8192.
INFO 05-20 18:15:53 [vllm.py:886] Asynchronous scheduling is enabled.
INFO 05-20 18:15:53 [kernel.py:212] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
Multiple valid tokenizer files found. Using tokenizer.model.v3.
tokenizer.model.v3: 100% 587k/587k [00:00<00:00, 20.3MB/s]
generation_config.json: 100% 116/116 [00:00<00:00, 694kB/s]
(EngineCore pid=3468) INFO 05-20 18:15:54 [core.py:109] Initializing a V1 LLM engine (v0.21.0) with config: model='mistralai/Mistral-7B-v0.3', speculative_config=None, tokenizer='mistralai/Mistral-7B-v0.3', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=False, quantization=None, quantization_config=None, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=mistralai/Mistral-7B-v0.3, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'ir_enable_torch_wrap': True, 'splitting_ops': ['vllm::unified_attention_with_output', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::gdn_attention_core_xpu', 'vllm::olmo_hybrid_gdn_full_forward', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::deepseek_v4_attention', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update'], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': [], 'compile_ranges_endpoints': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': 512, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=False, moe_backend='auto')
(EngineCore pid=3468) INFO 05-20 18:15:54 [parallel_state.py:1410] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://172.28.0.12:36189 backend=nccl
(EngineCore pid=3468) INFO 05-20 18:15:54 [parallel_state.py:1723] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A, EPLB rank N/A
(EngineCore pid=3468) INFO 05-20 18:15:57 [topk_topp_sampler.py:45] Using FlashInfer for top-p & top-k sampling.
(EngineCore pid=3468) INFO 05-20 18:15:57 [gpu_model_runner.py:4857] Starting to load model mistralai/Mistral-7B-v0.3...
(EngineCore pid=3468) ERROR 05-20 18:15:58 [fa_utils.py:171] Cannot use FA version 2 is not supported due to FA2 is only supported on devices with compute capability >= 8
(EngineCore pid=3468) INFO 05-20 18:15:58 [cuda.py:372] Using FLASHINFER attention backend out of potential backends: ['FLASHINFER', 'TRITON_ATTN', 'FLEX_ATTENTION'].
(EngineCore pid=3468) INFO 05-20 18:20:36 [weight_utils.py:619] Time spent downloading weights for mistralai/Mistral-7B-v0.3: 276.902556 seconds
(EngineCore pid=3468) INFO 05-20 18:20:36 [weight_utils.py:663] No consolidated.safetensors.index.json found in remote.
(EngineCore pid=3468) INFO 05-20 18:20:36 [weight_utils.py:938] Filesystem type for checkpoints: OVERLAY. Checkpoint size: 13.50 GiB. Available RAM: 7.19 GiB.
(EngineCore pid=3468) INFO 05-20 18:20:36 [weight_utils.py:968] Auto-prefetch is disabled because the filesystem (OVERLAY) is not a recognized network FS (NFS/Lustre) and the checkpoint size (13.50 GiB) exceeds 90% of available RAM (7.19 GiB).
Loading safetensors checkpoint shards: 100% 1/1 [00:59<00:00, 59.98s/it]
(EngineCore pid=3468) INFO 05-20 18:21:36 [default_loader.py:397] Loading weights took 60.11 seconds
(EngineCore pid=3468) INFO 05-20 18:21:37 [gpu_model_runner.py:4959] Model loading took 13.51 GiB memory and 338.217966 seconds
(EngineCore pid=3468) INFO 05-20 18:21:49 [backends.py:1089] Using cache directory: /root/.cache/vllm/torch_compile_cache/336fe99a7b/rank_0_0/backbone for vLLM's torch.compile
(EngineCore pid=3468) INFO 05-20 18:21:49 [backends.py:1148] Dynamo bytecode transform time: 11.21 s
(EngineCore pid=3468) [rank0]:W0520 18:21:51.292000 3468 torch/_inductor/utils.py:1731] Not enough SMs to use max_autotune_gemm mode
(EngineCore pid=3468) INFO 05-20 18:21:55 [backends.py:378] Cache the graph of compile range (1, 8192) for later use
(EngineCore pid=3468) INFO 05-20 18:22:01 [backends.py:393] Compiling a graph for compile range (1, 8192) takes 12.22 s
(EngineCore pid=3468) INFO 05-20 18:22:06 [decorators.py:708] saved AOT compiled function to /root/.cache/vllm/torch_compile_cache/torch_aot_compile/ec2cf0f58dbd2ce76ddf55b6d1b46a6464ad228569439873df7290a7b1db4503/rank_0_0/model
(EngineCore pid=3468) INFO 05-20 18:22:06 [monitor.py:53] torch.compile took 27.95 s in total
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140] EngineCore failed to start.
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140] Traceback (most recent call last):
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 1114, in run_engine_core
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]     engine_core = EngineCoreProc(*args, engine_index=dp_rank, **kwargs)
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]   File "/usr/local/lib/python3.12/dist-packages/vllm/tracing/otel.py", line 178, in sync_wrapper
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]     return func(*args, **kwargs)
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 880, in __init__
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]     super().__init__(
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 128, in __init__
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]     kv_cache_config = self._initialize_kv_caches(vllm_config)
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]   File "/usr/local/lib/python3.12/dist-packages/vllm/tracing/otel.py", line 178, in sync_wrapper
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]     return func(*args, **kwargs)
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 250, in _initialize_kv_caches
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]     available_gpu_memory = self.model_executor.determine_available_memory()
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/executor/abstract.py", line 147, in determine_available_memory
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]     return self.collective_rpc("determine_available_memory")
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/executor/uniproc_executor.py", line 93, in collective_rpc
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]     result = run_method(self.driver_worker, method, args, kwargs)
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/serial_utils.py", line 510, in run_method
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]     return func(*args, **kwargs)
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]   File "/usr/local/lib/python3.12/dist-packages/torch/utils/_contextlib.py", line 124, in decorate_context
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]     return func(*args, **kwargs)
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/worker/gpu_worker.py", line 392, in determine_available_memory
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]     self.model_runner.profile_run()
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/worker/gpu_model_runner.py", line 5948, in profile_run
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]     hidden_states, last_hidden_states = self._dummy_run(
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]                                         ^^^^^^^^^^^^^^^^
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]   File "/usr/local/lib/python3.12/dist-packages/torch/utils/_contextlib.py", line 124, in decorate_context
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]     return func(*args, **kwargs)
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/worker/gpu_model_runner.py", line 5616, in _dummy_run
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]     outputs = self.model(
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]               ^^^^^^^^^^^
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]   File "/usr/local/lib/python3.12/dist-packages/vllm/compilation/cuda_graph.py", line 254, in __call__
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]     return self.runnable(*args, **kwargs)
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1779, in _wrapped_call_impl
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]     return self._call_impl(*args, **kwargs)
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1790, in _call_impl
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]     return forward_call(*args, **kwargs)
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/llama.py", line 572, in forward
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]     model_output = self.model(
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]                    ^^^^^^^^^^^
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]   File "/usr/local/lib/python3.12/dist-packages/vllm/compilation/decorators.py", line 670, in __call__
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]     output = self.aot_compiled_fn(self, *args, **kwargs)
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]   File "/usr/local/lib/python3.12/dist-packages/torch/_dynamo/aot_compile.py", line 224, in __call__
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]     return self.fn(*args, **kwargs)
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]            ^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/mistral.py", line 217, in forward
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]     def forward(
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]   File "/usr/local/lib/python3.12/dist-packages/vllm/compilation/caching.py", line 217, in __call__
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]     return self.optimized_call(*args, **kwargs)
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]   File "<string>", line 175, in execution_fn
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]   File "/usr/local/lib/python3.12/dist-packages/vllm/compilation/cuda_graph.py", line 254, in __call__
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]     return self.runnable(*args, **kwargs)
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]   File "/usr/local/lib/python3.12/dist-packages/vllm/compilation/piecewise_backend.py", line 380, in __call__
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]     return range_entry.runnable(*args)
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]   File "/usr/local/lib/python3.12/dist-packages/torch/_inductor/standalone_compile.py", line 122, in __call__
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]     return self._compiled_fn(*args)
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]            ^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]   File "/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py", line 1263, in _fn
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]     return fn(*args, **kwargs)
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]            ^^^^^^^^^^^^^^^^^^^
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]   File "/usr/local/lib/python3.12/dist-packages/torch/_functorch/aot_autograd.py", line 1200, in forward
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]     return compiled_fn(full_args)
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]            ^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]   File "/usr/local/lib/python3.12/dist-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 580, in runtime_wrapper
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]     all_outs = call_func_at_runtime_with_args(
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]   File "/usr/local/lib/python3.12/dist-packages/torch/_functorch/_aot_autograd/utils.py", line 138, in call_func_at_runtime_with_args
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]     out = normalize_as_list(f(args))
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]                             ^^^^^^^
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]   File "/usr/local/lib/python3.12/dist-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 2298, in __call__
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]     return self.compiled_fn(*args, **kwargs)
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]   File "/usr/local/lib/python3.12/dist-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 783, in wrapper
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]     return compiled_fn(runtime_args)
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]            ^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]   File "/usr/local/lib/python3.12/dist-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 1011, in inner_fn
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]     outs = compiled_fn(args)
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]            ^^^^^^^^^^^^^^^^^
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]   File "/usr/local/lib/python3.12/dist-packages/torch/_inductor/output_code.py", line 656, in __call__
(EngineCore pid=3468) ERROR 05-20 18:22:06 [core.py:1140]     return self.current_callable(inputs)

**Associer Google Drive pour la sauvgarde de résultats**

In [ ]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

**Création des dossiers des résultats sur Drive**

In [ ]:
import os

MODEL_PATH = "mistralai/Mistral-7B-Instruct-v0.3"

BASE_DIR = "/content/drive/MyDrive/H-Neurons-results/Mistral-7b"

RESPONSES_PATH = f"{BASE_DIR}/responses_test.jsonl"

ANSWER_TOKENS_3CLASS_PATH = f"{BASE_DIR}/answer_tokens_3class.jsonl"
BALANCED_IDS_3CLASS_PATH = f"{BASE_DIR}/balanced_ids_3class_3000.json"

ACTIVATIONS_3CLASS_ROOT = f"{BASE_DIR}/activations_3class"
CLASSIFIER_3CLASS_DIR = f"{BASE_DIR}/classifier_3class"

os.makedirs(BASE_DIR, exist_ok=True)
os.makedirs(ACTIVATIONS_3CLASS_ROOT, exist_ok=True)
os.makedirs(CLASSIFIER_3CLASS_DIR, exist_ok=True)

print("MODEL_PATH:", MODEL_PATH)
print("RESPONSES_PATH:", RESPONSES_PATH)
print("ANSWER_TOKENS_3CLASS_PATH:", ANSWER_TOKENS_3CLASS_PATH)

assert os.path.exists(RESPONSES_PATH), f"Fichier introuvable : {RESPONSES_PATH}"
print("Fichier responses trouvé.")

MODEL_PATH: mistralai/Mistral-7B-Instruct-v0.3
RESPONSES_PATH: /content/drive/MyDrive/H-Neurons-results/Mistral-7b/responses_test.jsonl
ANSWER_TOKENS_3CLASS_PATH: /content/drive/MyDrive/H-Neurons-results/Mistral-7b/answer_tokens_3class.jsonl
Fichier responses trouvé.

**Nous utilisons ce code pour nettoyer les données brutes. Son rôle est d'isoler le token exact (le mot précis, par exemple "Berlin") où le modèle commet l'hallucination ou dit la vérité.**

In [ ]:
import json #bibliothèque pour manipuler fichier json
import os # pour manipuler les fichers
import re #pour les taches de normalisation
from collections import Counter #
from tqdm import tqdm
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained(
    MODEL_PATH,
    trust_remote_code=True
)

def normalize_text(text):
    return re.sub(r"\s+", " ", str(text)).strip()


def get_class_label(judges):
    """
    t = toutes les réponses valides sont correctes
    f = toutes les réponses valides sont incorrectes
    m = mélange true / false
    """
    valid = [j for j in judges if j in ["true", "false"]]

    if len(valid) == 0:
        return None

    if all(j == "true" for j in valid):
        return "t"

    if all(j == "false" for j in valid):
        return "f"

    return "m"


def choose_representative_response(responses, judges, class_label):
    """
    On garde la logique repo-style :
    une seule réponse représentative par question.
    """
    valid_indices = [i for i, j in enumerate(judges) if j in ["true", "false"]]

    if class_label == "t":
        indices = [i for i in valid_indices if judges[i] == "true"]

    elif class_label == "f":
        indices = [i for i in valid_indices if judges[i] == "false"]

    else:
        indices = valid_indices

    selected_responses = [responses[i] for i in indices]

    return Counter(selected_responses).most_common(1)[0][0]


def get_ground_truth_aliases(ground_truth):
    aliases = []

    if isinstance(ground_truth, str):
        aliases.append(ground_truth)

    elif isinstance(ground_truth, list):
        aliases.extend([str(x) for x in ground_truth])

    elif isinstance(ground_truth, dict):
        for key in ["value", "normalized_value"]:
            if key in ground_truth and ground_truth[key]:
                aliases.append(str(ground_truth[key]))

        for key in ["aliases", "normalized_aliases", "human_answers"]:
            if key in ground_truth and isinstance(ground_truth[key], list):
                aliases.extend([str(x) for x in ground_truth[key]])

    aliases = [normalize_text(a) for a in aliases if normalize_text(a)]
    aliases = list(dict.fromkeys(aliases))
    aliases = sorted(aliases, key=len, reverse=True)

    return aliases


def find_answer_text_in_response(response, ground_truth):
    """
    Pour les réponses correctes, on essaie de trouver l'alias du ground truth
    dans la réponse générée.
    """
    aliases = get_ground_truth_aliases(ground_truth)
    response_low = response.lower()

    for alias in aliases:
        alias_low = alias.lower()

        if alias_low in response_low:
            return alias

    return None


def heuristic_answer_text(response):
    """
    Fallback sans API :
    on extrait une réponse courte depuis la génération.
    """
    response = normalize_text(response)

    patterns = [
        r"(?i)(?:the answer is|answer:|final answer:|it is|it's|this is)\s+(.+)",
        r"(?i)(?:la réponse est|réponse\s*:)\s+(.+)"
    ]

    for pattern in patterns:
        match = re.search(pattern, response)

        if match:
            ans = match.group(1).strip()
            ans = re.split(r"[.;\n]", ans)[0].strip()

            words = ans.split()
            if len(words) > 20:
                ans = " ".join(words[:20])

            return ans

    first_sentence = re.split(r"[.;\n]", response)[0].strip()

    words = first_sentence.split()
    if len(words) > 20:
        first_sentence = " ".join(words[:20])

    return first_sentence


def tokens_from_answer_text(response, answer_text):
    """
    Convertit answer_text en tokens du tokenizer.
    Les tokens doivent appartenir à la réponse tokenisée.
    """
    tokenized_response = [
        tokenizer.decode([tid])
        for tid in tokenizer.encode(response, add_special_tokens=False)
    ]

    answer_tokens = [
        tokenizer.decode([tid])
        for tid in tokenizer.encode(answer_text, add_special_tokens=False)
    ]

    # Vérification simple : les tokens extraits doivent être présents dans la réponse.
    valid_answer_tokens = [tok for tok in answer_tokens if tok in tokenized_response]

    if len(valid_answer_tokens) == 0:
        # fallback repo-compatible : on prend toute la première phrase
        fallback_text = heuristic_answer_text(response)
        valid_answer_tokens = [
            tokenizer.decode([tid])
            for tid in tokenizer.encode(fallback_text, add_special_tokens=False)
        ]

        valid_answer_tokens = [
            tok for tok in valid_answer_tokens
            if tok in tokenized_response
        ]

    return tokenized_response, valid_answer_tokens


# Si tu veux recommencer proprement, supprime l'ancien fichier
if os.path.exists(ANSWER_TOKENS_3CLASS_PATH):
    os.remove(ANSWER_TOKENS_3CLASS_PATH)
    print("Ancien fichier supprimé :", ANSWER_TOKENS_3CLASS_PATH)


written = 0
skipped = 0
empty_answer_tokens = 0
class_counts = Counter()

with open(RESPONSES_PATH, "r", encoding="utf-8") as f_in, \
     open(ANSWER_TOKENS_3CLASS_PATH, "w", encoding="utf-8") as f_out:

    for line in tqdm(f_in, desc="Extract answer tokens sans API"):
        if not line.strip():
            continue

        obj = json.loads(line)
        qid = list(obj.keys())[0]
        data = obj[qid]

        question = data["question"]
        responses = data["responses"]
        judges = data["judges"]
        ground_truth = data.get("ground_truth", None)

        class_label = get_class_label(judges)

        if class_label is None:
            skipped += 1
            continue

        rep_response = choose_representative_response(
            responses=responses,
            judges=judges,
            class_label=class_label
        )

        rep_response = normalize_text(rep_response)

        # Pour t : on essaie de trouver le ground truth dans la réponse.
        if class_label == "t":
            answer_text = find_answer_text_in_response(rep_response, ground_truth)

            if answer_text is None:
                answer_text = heuristic_answer_text(rep_response)

        # Pour f et m : sans API, on extrait une réponse courte heuristique.
        else:
            answer_text = heuristic_answer_text(rep_response)

        tokenized_response, answer_tokens = tokens_from_answer_text(
            response=rep_response,
            answer_text=answer_text
        )

        if len(answer_tokens) == 0:
            empty_answer_tokens += 1
            skipped += 1
            continue

        result = {
            qid: {
                "question": question,
                "response": rep_response,
                "tokenized_response": tokenized_response,
                "answer_tokens": answer_tokens,
                "judge": class_label,
                "original_judges": judges,
                "ground_truth": ground_truth,
                "answer_text_heuristic": answer_text
            }
        }

        f_out.write(json.dumps(result, ensure_ascii=False) + "\n")

        written += 1
        class_counts[class_label] += 1

print("Fichier créé :", ANSWER_TOKENS_3CLASS_PATH)
print("Écrits :", written)
print("Ignorés :", skipped)
print("Answer tokens vides :", empty_answer_tokens)
print("Distribution :", class_counts)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:112: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/601 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/141k [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tokenizer.model:   0%|          | 0.00/587k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.96M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/414 [00:00<?, ?B/s]

Extract answer tokens sans API: 10000it [00:03, 2798.18it/s]

Fichier créé : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/answer_tokens_3class.jsonl
Écrits : 10000
Ignorés : 0
Answer tokens vides : 0
Distribution : Counter({'t': 5920, 'f': 2353, 'm': 1727})

In [ ]:
import os

assert os.path.exists(ANSWER_TOKENS_3CLASS_PATH), ANSWER_TOKENS_3CLASS_PATH
print("Fichier answer_tokens trouvé :", ANSWER_TOKENS_3CLASS_PATH)

Fichier answer_tokens trouvé : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/answer_tokens_3class.jsonl

**Ce code parcourt notre fichier de données préparées pour compter et afficher le nombre total de questions classées dans chaque catégorie (vrai, faux, ou incertain/mixed)**

In [ ]:
import json
from collections import Counter

counts = Counter()

with open(ANSWER_TOKENS_3CLASS_PATH, "r", encoding="utf-8") as f:
    for line in f:
        obj = json.loads(line)
        qid = list(obj.keys())[0]
        label = obj[qid]["judge"]
        counts[label] += 1

print(counts)

Counter({'t': 5920, 'f': 2353, 'm': 1727})

**Ce code sélectionne un nombre égal de questions (idéalement 1000) pour chacune des trois classes (vrai, faux, incertain) afin de créer un échantillon d'entraînement ou d'analyse parfaitement équilibré.**

In [ ]:
%%writefile scripts/sample_balanced_ids_3class.py
import json
import argparse
import random
from tqdm import tqdm


def parse_args():
    parser = argparse.ArgumentParser(description="Sample balanced t/f/m IDs.")
    parser.add_argument("--input_path", type=str, required=True)
    parser.add_argument("--output_path", type=str, required=True)
    parser.add_argument("--num_samples", type=int, default=1000)
    parser.add_argument("--seed", type=int, default=42)
    return parser.parse_args()


def main():
    args = parse_args()
    random.seed(args.seed)

    ids = {
        "t": [],
        "f": [],
        "m": []
    }

    with open(args.input_path, "r", encoding="utf-8") as f:
        for line in tqdm(f, desc="Reading answer_tokens"):
            if not line.strip():
                continue

            obj = json.loads(line)
            qid = list(obj.keys())[0]
            label = obj[qid].get("judge")

            if label in ids:
                ids[label].append(qid)

    print("Available IDs:")
    print("t:", len(ids["t"]))
    print("f:", len(ids["f"]))
    print("m:", len(ids["m"]))

    n = min(
        args.num_samples,
        len(ids["t"]),
        len(ids["f"]),
        len(ids["m"])
    )

    if n < args.num_samples:
        print(f"Warning: seulement {n} exemples disponibles par classe.")

    output = {
        "t": random.sample(ids["t"], n),
        "f": random.sample(ids["f"], n),
        "m": random.sample(ids["m"], n)
    }

    with open(args.output_path, "w", encoding="utf-8") as f:
        json.dump(output, f, indent=4, ensure_ascii=False)

    print("Balanced IDs saved to:", args.output_path)
    print("t:", len(output["t"]))
    print("f:", len(output["f"]))
    print("m:", len(output["m"]))
    print("total:", 3 * n)


if __name__ == "__main__":
    main()

Writing scripts/sample_balanced_ids_3class.py

**Ce bout de code lance le script pour piocher au hasard exactement 1000 questions par catégorie (vrai, faux, incertain) en utilisant une "graine" (seed 42) pour garantir que ce tirage aléatoire sera toujours le même si on relance l'expérience afin de garantir la reproductibilité**

In [ ]:
!python scripts/sample_balanced_ids_3class.py \
  --input_path "$ANSWER_TOKENS_3CLASS_PATH" \
  --output_path "$BALANCED_IDS_3CLASS_PATH" \
  --num_samples 1000 \
  --seed 42

Reading answer_tokens: 10000it [00:00, 70903.39it/s]
Available IDs:
t: 5920
f: 2353
m: 1727
Balanced IDs saved to: /content/drive/MyDrive/H-Neurons-results/Mistral-7b/balanced_ids_3class_3000.json
t: 1000
f: 1000
m: 1000
total: 3000

\**Le code suivant charge le fichier d'échantillons équilibrés (balanced_ids) pour vérifier le nombre d'identifiants par catégorie et s'assurer (grâce aux intersections) qu'aucune question n'a été classée par erreur dans plusieurs catégories à la fois (zéro doublon).**

In [ ]:
import json

with open(BALANCED_IDS_3CLASS_PATH, "r", encoding="utf-8") as f:
    balanced_ids = json.load(f)

print("t:", len(balanced_ids["t"]))
print("f:", len(balanced_ids["f"]))
print("m:", len(balanced_ids["m"]))
print("total:", len(balanced_ids["t"]) + len(balanced_ids["f"]) + len(balanced_ids["m"]))

print("t ∩ f:", len(set(balanced_ids["t"]) & set(balanced_ids["f"])))
print("t ∩ m:", len(set(balanced_ids["t"]) & set(balanced_ids["m"])))
print("f ∩ m:", len(set(balanced_ids["f"]) & set(balanced_ids["m"])))

t: 1000
f: 1000
m: 1000
total: 3000
t ∩ f: 0
t ∩ m: 0
f ∩ m: 0

In [ ]:
import os
import json

assert os.path.exists(BALANCED_IDS_3CLASS_PATH), BALANCED_IDS_3CLASS_PATH
assert os.path.exists(ANSWER_TOKENS_3CLASS_PATH), ANSWER_TOKENS_3CLASS_PATH

with open(BALANCED_IDS_3CLASS_PATH, "r", encoding="utf-8") as f:
    ids = json.load(f)

print("t:", len(ids["t"]))
print("f:", len(ids["f"]))
print("m:", len(ids["m"]))
print("total:", len(ids["t"]) + len(ids["f"]) + len(ids["m"]))

t: 1000
f: 1000
m: 1000
total: 3000

**Ce code modifie automatiquement l'ancien script "extract_activatoins" (qui ne gérait que les questions vraies et fausses) pour qu'il intègre désormais notre troisième catégorie d'incertitude (m), puis sauvegarde cette version mise à jour sous un nouveau fichier.**

In [ ]:
from pathlib import Path

src_path = Path("scripts/extract_activations.py")
dst_path = Path("scripts/extract_activations_3class.py")

src = src_path.read_text(encoding="utf-8")

old = 'target_ids = set(id_map["t"] + id_map["f"])'
new = 'target_ids = set(id_map["t"] + id_map["f"] + id_map["m"])'

if old not in src:
    print("Attention : ligne originale non trouvée. On affiche les lignes contenant target_ids :")
    for line in src.splitlines():
        if "target_ids" in line:
            print(line)
else:
    src = src.replace(old, new)

dst_path.write_text(src, encoding="utf-8")

print("Script créé :", dst_path)

Script créé : scripts/extract_activations_3class.py

In [ ]:
!grep -n "target_ids" scripts/extract_activations_3class.py

107:        target_ids = set(id_map["t"] + id_map["f"] + id_map["m"])
108:    print(f"Loaded {len(target_ids)} target IDs for extraction.")
119:        if qid not in target_ids:

In [ ]:
from pathlib import Path

path = Path("/content/H-Neurons/scripts/extract_activations_3class.py")

src = path.read_text(encoding="utf-8")

src = src.replace(
    "with torch.no_grad(): model(input_ids)",
    "with torch.no_grad():\n            model(**input_ids)"
)

path.write_text(src, encoding="utf-8")

print("Script corrigé.")

Script corrigé.

In [ ]:
from pathlib import Path

path = Path("/content/H-Neurons/scripts/extract_activations_3class.py")
src = path.read_text(encoding="utf-8")

start = src.index("def get_region_indices")
end = src.index("\ndef main", start)

new_function = '''
def get_region_indices(input_ids, tokenizer, question, response, answer_tokens):
    """
    Version compatible avec BatchEncoding / Tensor.
    Elle garde la logique du repo :
    - input
    - output
    - answer_tokens
    - all_except_answer_tokens
    """

    def to_id_list(x):
        # BatchEncoding
        if hasattr(x, "keys") and "input_ids" in x:
            x = x["input_ids"]

        # Tensor
        if hasattr(x, "detach"):
            x = x.detach().cpu()
            if len(x.shape) == 2:
                x = x[0]
            return [int(v) for v in x.tolist()]

        # tokenizers.Encoding
        if hasattr(x, "ids"):
            return [int(v) for v in x.ids]

        # liste
        if isinstance(x, (list, tuple)):
            if len(x) > 0 and hasattr(x[0], "ids"):
                return [int(v) for v in x[0].ids]
            if len(x) > 0 and isinstance(x[0], (list, tuple)):
                return [int(v) for v in x[0]]
            return [int(v) for v in x]

        raise TypeError(f"Type non supporté pour input_ids: {type(x)}")

    def find_subsequence(sequence, subsequence):
        if not subsequence:
            return -1

        n = len(subsequence)

        for i in range(len(sequence) - n + 1):
            if sequence[i:i+n] == subsequence:
                return i

        return -1

    full_ids = to_id_list(input_ids)

    full_tokens = [
        tokenizer.decode([tid])
        for tid in full_ids
    ]

    response_ids = tokenizer.encode(
        response,
        add_special_tokens=False
    )

    response_start = find_subsequence(full_ids, response_ids)

    if response_start == -1:
        response_start = 0
        response_end = len(full_ids)
    else:
        response_end = response_start + len(response_ids)

    input_indices = list(range(0, response_start))
    output_indices = list(range(response_start, response_end))

    # Chercher les answer_tokens dans les tokens complets
    answer_start = find_subsequence(full_tokens, answer_tokens)

    if answer_start != -1:
        answer_indices = list(range(answer_start, answer_start + len(answer_tokens)))
    else:
        answer_text = "".join(answer_tokens)

        answer_ids = tokenizer.encode(
            answer_text,
            add_special_tokens=False
        )

        answer_start = find_subsequence(full_ids, answer_ids)

        if answer_start != -1:
            answer_indices = list(range(answer_start, answer_start + len(answer_ids)))
        else:
            # fallback : si les answer_tokens ne matchent pas, on utilise tout output
            answer_indices = output_indices

    answer_set = set(answer_indices)

    all_except_answer_indices = [
        idx for idx in output_indices
        if idx not in answer_set
    ]

    if len(all_except_answer_indices) == 0:
        all_except_answer_indices = output_indices

    return {
        "input": input_indices,
        "output": output_indices,
        "answer_tokens": answer_indices,
        "all_except_answer_tokens": all_except_answer_indices
    }

'''

src = src[:start] + new_function + src[end:]

# Corriger aussi l'appel modèle si ce n'est pas déjà fait
src = src.replace(
    "with torch.no_grad(): model(input_ids)",
    "with torch.no_grad():\\n            model(**input_ids)"
)

path.write_text(src, encoding="utf-8")

print("Patch appliqué avec succès.")

Patch appliqué avec succès.

In [ ]:
from pathlib import Path

path = Path("/content/H-Neurons/scripts/extract_activations_3class.py")
src = path.read_text(encoding="utf-8")

start = src.index("def get_region_indices")
end = src.index("\ndef main", start)

new_function = '''
def get_region_indices(input_ids, tokenizer, question, response, answer_tokens):
    """
    Version compatible avec BatchEncoding / Tensor,
    mais qui garde le format attendu par le repo :
    chaque région est un intervalle [start, end].
    """

    def to_id_list(x):
        if hasattr(x, "keys") and "input_ids" in x:
            x = x["input_ids"]

        if hasattr(x, "detach"):
            x = x.detach().cpu()
            if len(x.shape) == 2:
                x = x[0]
            return [int(v) for v in x.tolist()]

        if hasattr(x, "ids"):
            return [int(v) for v in x.ids]

        if isinstance(x, (list, tuple)):
            if len(x) > 0 and hasattr(x[0], "ids"):
                return [int(v) for v in x[0].ids]
            if len(x) > 0 and isinstance(x[0], (list, tuple)):
                return [int(v) for v in x[0]]
            return [int(v) for v in x]

        raise TypeError(f"Type non supporté pour input_ids: {type(x)}")

    def find_subsequence(sequence, subsequence):
        if not subsequence:
            return -1

        n = len(subsequence)

        for i in range(len(sequence) - n + 1):
            if sequence[i:i+n] == subsequence:
                return i

        return -1

    full_ids = to_id_list(input_ids)

    full_tokens = [
        tokenizer.decode([tid])
        for tid in full_ids
    ]

    # Région output = réponse du modèle
    response_ids = tokenizer.encode(
        response,
        add_special_tokens=False
    )

    response_start = find_subsequence(full_ids, response_ids)

    if response_start == -1:
        # fallback : considérer toute la séquence comme output
        response_start = 0
        response_end = len(full_ids)
    else:
        response_end = response_start + len(response_ids)

    # Région answer_tokens
    answer_start = find_subsequence(full_tokens, answer_tokens)

    if answer_start != -1:
        answer_end = answer_start + len(answer_tokens)
    else:
        answer_text = "".join(answer_tokens)

        answer_ids = tokenizer.encode(
            answer_text,
            add_special_tokens=False
        )

        answer_start = find_subsequence(full_ids, answer_ids)

        if answer_start != -1:
            answer_end = answer_start + len(answer_ids)
        else:
            # fallback : utiliser tout output
            answer_start = response_start
            answer_end = response_end

    # Sécurités
    if answer_end <= answer_start:
        answer_start = response_start
        answer_end = response_end

    if response_end <= response_start:
        response_start = 0
        response_end = len(full_ids)

    # all_except_answer_tokens :
    # Le repo attend un seul intervalle [start, end].
    # Pour rester compatible, on prend output si impossible de faire mieux.
    if answer_start > response_start:
        all_except_start = response_start
        all_except_end = answer_start
    elif answer_end < response_end:
        all_except_start = answer_end
        all_except_end = response_end
    else:
        all_except_start = response_start
        all_except_end = response_end

    return {
        "input": [0, response_start],
        "output": [response_start, response_end],
        "answer_tokens": [answer_start, answer_end],
        "all_except_answer_tokens": [all_except_start, all_except_end]
    }

'''

src = src[:start] + new_function + src[end:]

# S'assurer aussi que le modèle reçoit bien un BatchEncoding dépaqueté
src = src.replace(
    "with torch.no_grad(): model(input_ids)",
    "with torch.no_grad():\\n            model(**input_ids)"
)

path.write_text(src, encoding="utf-8")

print("Patch appliqué : get_region_indices retourne maintenant des intervalles [start, end].")

Patch appliqué : get_region_indices retourne maintenant des intervalles [start, end].

**lancer le script extract_activations_3class.py**

In [ ]:
%cd /content/H-Neurons

!python scripts/extract_activations_3class.py \
  --model_path "$MODEL_PATH" \
  --input_path "$ANSWER_TOKENS_3CLASS_PATH" \
  --train_ids_path "$BALANCED_IDS_3CLASS_PATH" \
  --output_root "$ACTIVATIONS_3CLASS_ROOT" \
  --locations answer_tokens \
  --method mean \
  --use_mag \
  --use_abs

/content/H-Neurons
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
[transformers] `torch_dtype` is deprecated! Use `dtype` instead!
model.safetensors.index.json: 100% 23.9k/23.9k [00:00<00:00, 52.8MB/s]
Downloading (incomplete total...): 0.00B [00:00, ?B/s]
Downloading (incomplete total...):  93% 13.5G/14.5G [00:41<00:02, 451MB/s]
Downloading (incomplete total...):  96% 13.9G/14.5G [00:44<00:01, 330MB/s]
Downloading (incomplete total...): 100% 14.5G/14.5G [00:44<00:00, 441MB/s]
Fetching 3 files: 100% 3/3 [00:44<00:00, 14.79s/it]
Download complete: 100% 14.5G/14.5G [00:44<00:00, 326MB/s]
Loading weights: 100% 291/291 [00:03<00:00, 77.12it/s]
generation_config.json: 100% 116/116 [00:00<00:00, 659kB/s]
Loaded 3000 target IDs for extraction.
Processing:  85% 8481/10000 [02:41<00:51, 29.42it/s]

In [ ]:
import os
from pathlib import Path
MODEL_PATH = "mistralai/Mistral-7B-v0.3"   #Il suffit de changer le modèle

BASE_DIR = "/content/drive/MyDrive/H-Neurons-results/Mistral-7b" # mettre ton dossier de base


ANSWER_TOKENS_3CLASS_PATH = f"{BASE_DIR}/answer_tokens_3class.jsonl" #fichier des answers tokens
BALANCED_IDS_3CLASS_PATH = f"{BASE_DIR}/balanced_ids_3class_3000.json" #fichier des balanced_IDs

ACTIVATIONS_3CLASS_ROOT = f"{BASE_DIR}/activations_3class" # chemin vers les activations
ACTIVATIONS_ANSWER_TOKENS_DIR = f"{ACTIVATIONS_3CLASS_ROOT}/answer_tokens"

CLASSIFIER_3CLASS_DIR = f"{BASE_DIR}/classifier-L2-3classes"  # dossier pour sauvegarder les résultats

for directory in [
    BASE_DIR,
    ACTIVATIONS_3CLASS_ROOT,
    CLASSIFIER_3CLASS_DIR
]:
    os.makedirs(directory, exist_ok=True)

print("MODEL_PATH:", MODEL_PATH)
print("BASE_DIR:", BASE_DIR)


assert os.path.exists(BALANCED_IDS_3CLASS_PATH), BALANCED_IDS_3CLASS_PATH
assert os.path.exists(ACTIVATIONS_ANSWER_TOKENS_DIR), ACTIVATIONS_ANSWER_TOKENS_DIR

print("IDs équilibrés :", BALANCED_IDS_3CLASS_PATH)
print("Activations :", ACTIVATIONS_ANSWER_TOKENS_DIR)
print("Sortie classifieurs L2 :", CLASSIFIER_3CLASS_DIR)

MODEL_PATH: mistralai/Mistral-7B-v0.3
BASE_DIR: /content/drive/MyDrive/H-Neurons-results/Mistral-7b
IDs équilibrés : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/balanced_ids_3class_3000.json
Activations : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens
Sortie classifieurs L2 : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/classifier-L2-3classes

In [ ]:
import os
import numpy as np
import pandas as pd
from tqdm import tqdm

**Charger les activations**

In [ ]:
import os
import numpy as np
import pandas as pd
from tqdm import tqdm

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix
)

# ============================================================
# 1. Paramètres
# ============================================================

act_path = "/content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens"

output_dir = "/content/drive/MyDrive/H-Neurons-results/Mistral-7b/classifier-L2-3classes"

NUM_LAYERS = 32
HIDDEN_SIZE = 14336

# Labels :
# 0 = correct / true
# 1 = false / hallucination
# 2 = uncertain
label_names = {
    0: "true_correct",
    1: "false_hallucination",
    2: "uncertain"
}

# Si dans ton dictionnaire la classe uncertain s'appelle "u"
# on utilise "u". Sinon, on essaie "uncertain".
uncertain_key = "m" if "m" in qids_data else "uncertain"

class_config = [
    ("t", 0, "Chargement activations correctes"),
    ("f", 1, "Chargement activations fausses"),
    (uncertain_key, 2, "Chargement activations uncertain")
]

# ============================================================
# 2. Chargement des activations des 3 classes
# ============================================================

X = []
y = []
qids = []

for key, label, desc in class_config:
    print(f"\nClasse {key} -> label {label} : {label_names[label]}")

    # Use a local list to store qids for tqdm to get the correct total count
    current_class_qids = qids_data[key]

    for qid in tqdm(current_class_qids, desc=desc):
        file_path = os.path.join(act_path, f"act_{qid}.npy")

        if not os.path.exists(file_path):
            print(f"WARNING: Fichier manquant, saut du fichier : {file_path}")
            continue # Skip to the next qid if the file is missing

        arr = np.load(file_path).astype(np.float32)

        if arr.shape != (NUM_LAYERS, HIDDEN_SIZE):
            print(
                f"WARNING: Shape inattendue pour {qid} : {arr.shape}, attendu {(NUM_LAYERS, HIDDEN_SIZE)}. Saut du fichier."
            )
            continue # Skip to the next qid if the shape is incorrect

        X.append(arr.reshape(-1))
        y.append(label)
        qids.append(qid)

X = np.stack(X)
y = np.array(y)
qids = np.array(qids)

print("\nChargement terminé.")
print("Shape X :", X.shape)
print("Shape y :", y.shape)
print("Labels :", dict(zip(*np.unique(y, return_counts=True))))

if X.shape[0] != 3000:
    print(f"Attention : tu n'as pas 3000 exemples, mais {X.shape[0]} exemples.")

Classe t -> label 0 : true_correct

Chargement activations correctes:   5%|▌         | 50/1000 [00:00<00:01, 487.76it/s]

WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5452.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4583.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3529.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2827.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6100.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3782.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4559.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1624.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2623.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3067.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4767.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4045.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6780.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5634.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6513.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3778.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1583.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2747.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2074.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4540.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4692.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6456.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1632.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4689.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2493.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4810.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4273.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2277.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3635.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3884.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5253.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5080.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4328.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6576.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5830.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2938.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4691.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2174.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5373.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5970.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4323.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6524.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6216.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5612.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4918.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5360.npy

Chargement activations correctes:  16%|█▋        | 165/1000 [00:00<00:01, 537.49it/s]

WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3601.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3528.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2326.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4429.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5456.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6285.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3956.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2729.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6232.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2969.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1280.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4336.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2387.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4133.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6829.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2427.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5736.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2956.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1194.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5508.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2265.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4277.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3562.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4047.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3677.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4170.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4456.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1726.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4433.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1255.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2715.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3144.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2847.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5241.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6166.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1626.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4659.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4652.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2420.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3511.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3727.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3907.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6164.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6873.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6198.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3645.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4320.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5473.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1836.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2177.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6915.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6851.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4195.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2977.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3114.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5207.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5443.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4915.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3682.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3532.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4721.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2775.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3264.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3352.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4137.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2733.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3578.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5803.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2555.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3847.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4302.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3492.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4875.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1638.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2411.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3680.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6316.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6736.npy

Chargement activations correctes:  28%|██▊       | 276/1000 [00:00<00:01, 527.47it/s]

WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1245.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6003.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1895.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3288.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2127.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3585.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2854.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4521.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3914.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2988.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4522.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2735.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6652.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5284.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2967.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3236.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3226.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4700.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5953.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2724.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2459.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4201.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4309.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2522.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3439.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2524.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1370.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5793.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1773.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1646.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1451.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2402.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6033.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5709.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5574.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1307.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3628.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3638.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2068.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2331.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3693.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1977.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3859.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5679.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3707.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3172.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1364.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2726.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2656.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2454.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1278.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1114.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4303.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2196.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_5043.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1637.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6434.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3935.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5841.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6835.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2740.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2573.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4352.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3728.npy

Chargement activations correctes:  39%|███▉      | 388/1000 [00:00<00:01, 529.71it/s]

WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4441.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2580.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3012.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3544.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3116.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4638.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6074.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3131.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1320.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4181.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3554.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4350.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4624.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5101.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1579.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5769.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4434.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4097.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3394.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4112.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5961.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6791.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3253.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4306.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1196.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5558.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2243.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2256.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5136.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4069.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3655.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2447.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3077.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3505.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_5038.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1896.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3748.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6558.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4969.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5718.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3508.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5941.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3923.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5870.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4524.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4879.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4840.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6823.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6276.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5346.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4237.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3070.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3722.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5348.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4635.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5409.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4148.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1957.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3874.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6596.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1706.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4037.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6335.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3784.npy

Chargement activations correctes:  49%|████▉     | 492/1000 [00:00<00:01, 459.78it/s]

WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4410.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3891.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1745.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2342.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6201.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3685.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5927.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4018.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5127.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3176.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1474.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1463.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5963.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3619.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6506.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2478.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2810.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2299.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2935.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2824.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5806.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1240.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4701.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4715.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5485.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3143.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1259.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6151.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4135.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4378.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4305.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4665.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1831.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1866.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4870.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3194.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4317.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3856.npy

Chargement activations correctes:  59%|█████▉    | 594/1000 [00:01<00:00, 473.70it/s]

WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6670.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1857.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3337.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3667.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6266.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6849.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5973.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1777.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5883.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5170.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6855.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3105.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1396.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1303.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6440.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3920.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1599.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5893.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6111.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5041.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4175.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1360.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3826.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_5145.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1747.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4367.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5727.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2372.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1964.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6079.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2453.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3181.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2527.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5790.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4977.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3252.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5877.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5323.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5095.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3125.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6026.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2554.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4965.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2204.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1499.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5264.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4298.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6833.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6429.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2871.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1257.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3481.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5746.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6278.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1675.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2644.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6417.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3302.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2366.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3961.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3643.npy

Chargement activations correctes:  71%|███████   | 709/1000 [00:01<00:00, 514.83it/s]

WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2228.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2367.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5934.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3546.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3991.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4645.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1968.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4985.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6846.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3052.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1695.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2026.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2547.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2100.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4090.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3568.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5417.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4679.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3362.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2716.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5227.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3260.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4567.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1922.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6744.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_5071.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4460.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3699.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6387.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6612.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2455.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1511.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1382.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3738.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2385.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1521.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1595.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4440.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6414.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4299.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2583.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1577.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3665.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3799.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4803.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2753.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2770.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2719.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4538.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1854.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5951.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6144.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1330.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2407.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5158.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1169.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4581.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4086.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5862.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5507.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1730.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2321.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4102.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2408.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2192.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4694.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1617.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3743.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2473.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2846.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5641.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5671.npy

Chargement activations correctes:  76%|███████▌  | 761/1000 [00:01<00:00, 487.30it/s]

WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5141.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3250.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2531.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5958.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4082.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2614.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6482.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3919.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4862.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4886.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4348.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1215.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6763.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4585.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6331.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5236.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3437.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6226.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4746.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4112.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3579.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5837.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5605.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2794.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1814.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5372.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2288.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6634.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1843.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3372.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5647.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4433.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5045.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3663.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2697.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2371.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1846.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4595.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4343.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3537.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4707.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2111.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3473.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4187.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4937.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5943.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2757.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2413.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4009.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4742.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4656.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4629.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3938.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3274.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3391.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6859.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3931.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3285.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2571.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5569.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6718.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2802.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2063.npy

Chargement activations correctes:  82%|████████▏ | 819/1000 [00:01<00:00, 507.92it/s]

WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2785.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6351.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3455.npy

Chargement activations correctes:  93%|█████████▎| 929/1000 [00:01<00:00, 525.01it/s]

WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5880.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4389.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3910.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3543.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1678.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6542.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2179.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4446.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2997.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6882.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3627.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6319.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2547.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2709.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4631.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4543.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3435.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4667.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4934.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2934.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6659.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4563.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3908.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6444.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5422.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2804.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4268.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_5026.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2445.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2610.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1932.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3757.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2593.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1272.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2821.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4322.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5261.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6262.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4065.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3625.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3972.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1527.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2877.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3391.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2109.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1969.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4524.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1731.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4162.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5135.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4925.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5211.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4274.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5816.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3267.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3883.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1399.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6306.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4616.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2464.npy

Chargement activations correctes: 100%|██████████| 1000/1000 [00:01<00:00, 504.45it/s]

WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6630.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4932.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6544.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2185.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5205.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4547.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5828.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3771.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2856.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5609.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4307.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1907.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2429.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6292.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6486.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1306.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4523.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2976.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3696.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2859.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1892.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4705.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1788.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3703.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6056.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4287.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4503.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6017.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4419.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2475.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3311.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5666.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4472.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5358.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2465.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5968.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6380.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2890.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5852.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1269.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3856.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2194.npy

Classe f -> label 1 : false_hallucination

Chargement activations fausses:   0%|          | 0/1000 [00:00<?, ?it/s]

WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3573.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2043.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5280.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6021.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3732.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2353.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5420.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4812.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3195.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4094.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6172.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_5001.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3140.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4409.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3133.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6224.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6273.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2175.npy

Chargement activations fausses:  11%|█         | 108/1000 [00:00<00:01, 520.20it/s]

WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2549.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3711.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6854.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5076.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4269.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2448.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4365.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4055.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3235.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3520.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6242.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1397.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5043.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4456.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2434.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5034.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4114.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4751.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4588.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3319.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5923.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4407.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6261.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6038.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1244.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3484.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3129.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1377.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2914.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2259.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4084.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1322.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1446.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4729.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4897.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3174.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5643.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3555.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2237.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3980.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3998.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1820.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5818.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1288.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4533.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5994.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2946.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4988.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2662.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3025.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6427.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3233.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6782.npy

Chargement activations fausses:  16%|█▌        | 161/1000 [00:00<00:01, 487.30it/s]

WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1154.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2941.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3288.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5775.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2296.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1358.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3182.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4782.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2881.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3687.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3636.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3636.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3688.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3838.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4999.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3193.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2698.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3499.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6750.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1413.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4387.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3114.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1325.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1784.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4342.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4768.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4917.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2823.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2442.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3508.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3178.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6617.npy

Chargement activations fausses:  21%|██        | 210/1000 [00:00<00:01, 440.13it/s]

WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4890.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4225.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3737.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4334.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5677.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3953.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2591.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1808.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6584.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5681.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1723.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3994.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3475.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3912.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1315.npy

Chargement activations fausses:  26%|██▌       | 261/1000 [00:00<00:01, 437.17it/s]

WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2921.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4026.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2482.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3800.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5858.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2180.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4661.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6132.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1536.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3452.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2558.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6177.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6523.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4579.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6704.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4596.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2401.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3231.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3280.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1845.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4444.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5483.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3225.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2385.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2901.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6158.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4494.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6579.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5745.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3119.npy

Chargement activations fausses:  35%|███▌      | 350/1000 [00:00<00:01, 406.60it/s]

WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4046.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2626.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4154.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3366.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1543.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3730.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2593.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3563.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4081.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1639.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3471.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3016.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3882.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2764.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4340.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6765.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2693.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5653.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3318.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3476.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2487.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3385.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5189.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6864.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4334.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4658.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6572.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4885.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2653.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3579.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2377.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1796.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2787.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3161.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1406.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4440.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2972.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2364.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5557.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3270.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2390.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2650.npy

Chargement activations fausses:  43%|████▎     | 434/1000 [00:01<00:01, 405.96it/s]

WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5710.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2345.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4270.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4174.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6685.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5825.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2451.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5017.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2085.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4552.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6025.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4685.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4100.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3063.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4250.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4002.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1155.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6093.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3590.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4394.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4939.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_5025.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3635.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3188.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4688.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4679.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5977.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2672.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4115.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6324.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4946.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2024.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2358.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2667.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4601.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6574.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2201.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4555.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2430.npy

Chargement activations fausses:  48%|████▊     | 478/1000 [00:01<00:01, 412.43it/s]

WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5542.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6549.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3819.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5265.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3033.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4838.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5185.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4555.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6222.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4491.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4377.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4478.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1525.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4859.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5895.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3443.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6422.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5723.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2484.npy

Chargement activations fausses:  52%|█████▏    | 520/1000 [00:01<00:01, 379.67it/s]

WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5055.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3218.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2481.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5018.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3634.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1247.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3714.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4366.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3222.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3938.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6508.npy

Chargement activations fausses:  56%|█████▌    | 561/1000 [00:01<00:01, 386.57it/s]

WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4733.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3777.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5019.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1352.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4978.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3190.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3485.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1117.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4437.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5748.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4063.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5577.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5869.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4584.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2480.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2007.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6135.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6008.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6896.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2421.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5909.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2786.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2943.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6801.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4929.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3164.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5906.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4534.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1933.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4632.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5762.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4209.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4828.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2436.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2665.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2420.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3515.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5480.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5728.npy

Chargement activations fausses:  61%|██████▏   | 613/1000 [00:01<00:00, 422.89it/s]

WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3604.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4783.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1565.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5914.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6397.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3301.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4766.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3686.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5735.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1520.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5656.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4773.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2225.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2142.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5897.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6146.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1277.npy

Chargement activations fausses:  66%|██████▌   | 660/1000 [00:01<00:00, 424.88it/s]

WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1449.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3435.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2872.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3387.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4713.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2504.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_5051.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2539.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4744.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3730.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5903.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2468.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2941.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3326.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5102.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5815.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3957.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3944.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6293.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2730.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2855.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6628.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4781.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3631.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2863.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_5054.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4979.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5804.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4124.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2572.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4912.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4454.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4923.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4954.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5566.npy

Chargement activations fausses:  71%|███████   | 709/1000 [00:01<00:00, 443.03it/s]

WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2586.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6818.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6906.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2441.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2463.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2746.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3905.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4122.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1476.npy

Chargement activations fausses:  75%|███████▌  | 754/1000 [00:01<00:00, 417.92it/s]

WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3401.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5518.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4599.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6338.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4573.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3273.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3924.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2696.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6272.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2190.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5428.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3108.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3405.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3054.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4709.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5938.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3619.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2051.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3930.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1891.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3676.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2857.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3610.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5915.npy

Chargement activations fausses:  80%|███████▉  | 797/1000 [00:01<00:00, 407.35it/s]

WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3220.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5414.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6248.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5035.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3762.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4149.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1418.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5195.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3350.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2877.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4493.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1457.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6099.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6871.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3996.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1862.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5810.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6608.npy

Chargement activations fausses:  85%|████████▍ | 846/1000 [00:02<00:00, 427.99it/s]

WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2491.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2423.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6810.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2286.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2650.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1671.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4877.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2475.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2181.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3558.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3960.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6244.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3140.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2060.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2562.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3768.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6625.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6163.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6688.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4824.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2439.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4655.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2588.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2641.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3523.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3371.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3904.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5509.npy

Chargement activations fausses:  89%|████████▉ | 890/1000 [00:02<00:00, 427.59it/s]

WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5266.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5476.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2133.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5138.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2536.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6499.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4765.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2553.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3316.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6175.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4544.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5349.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1276.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4007.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3290.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6218.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1127.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5295.npy

Chargement activations fausses:  93%|█████████▎| 934/1000 [00:02<00:00, 422.87it/s]

WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2762.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3496.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6475.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4118.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5787.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3751.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6109.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6005.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2962.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2118.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3041.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3908.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3925.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4203.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1279.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4492.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2983.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4013.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2374.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4877.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4829.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3297.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5008.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2466.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3955.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_5086.npy

Chargement activations fausses:  98%|█████████▊| 977/1000 [00:02<00:00, 413.83it/s]

WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4268.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4321.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5924.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4694.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2266.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2763.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5481.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3902.npy

Chargement activations fausses: 100%|██████████| 1000/1000 [00:02<00:00, 419.50it/s]

WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5855.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4198.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6901.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4027.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2499.npy

Classe m -> label 2 : uncertain

Chargement activations uncertain:   5%|▌         | 52/1000 [00:00<00:01, 513.37it/s]

WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3261.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6343.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4179.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_5141.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5312.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4756.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3501.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4467.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4137.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6310.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1433.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6366.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5028.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2772.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6658.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1860.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2465.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2996.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3165.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3967.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2479.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2724.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2780.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4858.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4445.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3827.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5016.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3857.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2998.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3414.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6195.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4156.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3399.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4084.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1250.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6825.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5413.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4256.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2851.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4248.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6053.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6035.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3551.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4133.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4057.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4639.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2173.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2810.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4254.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4205.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4230.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6655.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5652.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2303.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1589.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4134.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_5033.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2860.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3632.npy

Chargement activations uncertain:  15%|█▌        | 154/1000 [00:00<00:01, 493.91it/s]

WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5177.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1391.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4783.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2130.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5978.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4647.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6694.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2939.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4510.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4816.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4293.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2920.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4046.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3720.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4762.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1931.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1822.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2362.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2574.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4788.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6423.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4592.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3404.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4052.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1136.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6249.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4049.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1979.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2274.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4185.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1948.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6116.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2804.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6308.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4854.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4874.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1545.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2312.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6070.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2900.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3473.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5578.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6367.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4262.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1389.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3694.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5684.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3420.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2495.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6916.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1402.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2645.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3008.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4750.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3710.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1422.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6797.npy

Chargement activations uncertain:  27%|██▋       | 268/1000 [00:00<00:01, 498.64it/s]

WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3363.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1946.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6601.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5567.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3214.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2618.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2992.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1674.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5435.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3445.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2619.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2400.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3866.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3208.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4906.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6389.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3436.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2137.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3459.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2352.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3666.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2257.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3055.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3409.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3254.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6767.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2357.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3460.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2597.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4332.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6541.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2553.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4426.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6894.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3525.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2824.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2840.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2912.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3709.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_5035.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4201.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1298.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6188.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4798.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5988.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4688.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3002.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6494.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3164.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2365.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6054.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4771.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2754.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6847.npy

Chargement activations uncertain:  32%|███▏      | 319/1000 [00:00<00:01, 473.40it/s]

WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4930.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2447.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6620.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4651.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2678.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3719.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4171.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1719.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4131.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4315.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2224.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5976.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4060.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1978.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6892.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5998.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3197.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2931.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4663.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4935.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4328.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6872.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2049.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4120.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6774.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1148.npy

Chargement activations uncertain:  37%|███▋      | 367/1000 [00:00<00:01, 459.77it/s]

WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4296.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3319.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6838.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2819.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1304.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6702.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2959.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2909.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4926.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3017.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2568.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2630.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3410.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1119.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1156.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1649.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2135.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2569.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4181.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3258.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6636.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2467.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2748.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3269.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2671.npy

Chargement activations uncertain:  42%|████▏     | 417/1000 [00:00<00:01, 467.20it/s]

WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2369.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2354.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5039.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1526.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3659.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3094.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4589.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5716.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2857.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4826.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2933.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5321.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2102.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5600.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4458.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3407.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1662.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3621.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1864.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3894.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4316.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2889.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4842.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6570.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2563.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4898.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4253.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3323.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5563.npy

Chargement activations uncertain:  46%|████▋     | 464/1000 [00:00<00:01, 463.72it/s]

WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3755.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2095.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2302.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1834.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4586.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4987.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3701.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6160.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6639.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3051.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5314.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3715.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1765.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2134.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6334.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2492.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4947.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4450.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1614.npy

Chargement activations uncertain:  51%|█████     | 511/1000 [00:01<00:01, 457.72it/s]

WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3227.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2766.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4819.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1940.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6672.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6737.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6112.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6336.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1709.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_5028.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6231.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2617.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3177.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2203.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3407.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3006.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3519.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5763.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4907.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4227.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3233.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3894.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2507.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3434.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2473.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2188.npy

Chargement activations uncertain:  56%|█████▌    | 557/1000 [00:01<00:01, 417.22it/s]

WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3976.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3968.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6045.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2660.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4622.npy

Chargement activations uncertain:  60%|██████    | 601/1000 [00:01<00:00, 421.87it/s]

WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4682.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6832.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3221.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4938.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3991.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6453.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3349.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2738.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4619.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5153.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5237.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2818.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2335.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6845.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3298.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5399.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4329.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4852.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1910.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1722.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3295.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2154.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1573.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5875.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6110.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4380.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6815.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1450.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3099.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1198.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5418.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4883.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1254.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3990.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4541.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_5004.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5640.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4030.npy

Chargement activations uncertain:  64%|██████▍   | 644/1000 [00:01<00:00, 408.48it/s]

WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5525.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5065.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6071.npy

Chargement activations uncertain:  69%|██████▊   | 686/1000 [00:01<00:00, 369.25it/s]

WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4331.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4633.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4539.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4441.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3746.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2119.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3881.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2488.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4549.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2683.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5331.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6455.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1963.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4455.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4913.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3971.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5477.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4959.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4736.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2987.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2138.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2033.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2708.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4995.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6303.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3609.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6696.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5644.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2041.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6046.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2851.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3506.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4680.npy

Chargement activations uncertain:  79%|███████▉  | 792/1000 [00:01<00:00, 443.44it/s]

WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1960.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3000.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3408.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5501.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1454.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4575.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3753.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4557.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4498.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5764.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6799.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2388.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3879.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4311.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4509.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1787.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6102.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4539.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5059.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1192.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5809.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2206.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3159.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1623.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6405.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2230.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2426.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1725.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3420.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2602.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2596.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6908.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2538.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1111.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4590.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6739.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4568.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1794.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4218.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5128.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6603.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2866.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6556.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3554.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6512.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4170.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4922.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2213.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1487.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3829.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4843.npy

Chargement activations uncertain:  90%|████████▉ | 899/1000 [00:01<00:00, 468.53it/s]

WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2141.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6241.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4777.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1555.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2906.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6345.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4072.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5739.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2086.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1581.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6227.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3331.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4447.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3787.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4374.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1826.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2425.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4952.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4011.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5560.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5383.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4582.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3675.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6078.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6283.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4593.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3258.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5215.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4182.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4602.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5594.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1888.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2639.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4192.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6412.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_5030.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2576.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6917.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1223.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2861.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4629.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6179.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3718.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2494.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3359.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4603.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5239.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3630.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2887.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3227.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3977.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3563.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6863.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2788.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4000.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1711.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2140.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4337.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4431.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1262.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6460.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4571.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5693.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6041.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4421.npy

Chargement activations uncertain: 100%|█████████▉| 996/1000 [00:02<00:00, 464.29it/s]

WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3086.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2336.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4488.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3811.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_2814.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6457.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2008.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4404.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1345.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3027.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6519.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6420.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3586.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4033.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3157.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3303.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1212.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4597.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4833.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5836.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3912.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2006.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6645.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5106.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5351.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_6773.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4570.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1552.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4530.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_1568.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2438.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2216.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_2839.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_3180.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_4844.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5981.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qz_5018.npy

Chargement activations uncertain: 100%|██████████| 1000/1000 [00:02<00:00, 452.33it/s]

WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_3268.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_5602.npy
WARNING: Fichier manquant, saut du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/activations_3class/answer_tokens/act_qb_4140.npy

Chargement terminé.
Shape X : (1393, 458752)
Shape y : (1393,)
Labels : {np.int64(0): np.int64(409), np.int64(1): np.int64(514), np.int64(2): np.int64(470)}
Attention : tu n'as pas 3000 exemples, mais 1393 exemples.

**Lancer le Classifier L2**

In [ ]:
import os
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score

# ============================================================
# Paramètres
# ============================================================

NUM_LAYERS = 32
HIDDEN_SIZE = 14336

DOMINANCE_THRESHOLD = 0.70   # classe dominante à au moins 70%
GAP_THRESHOLD = 0.20         # écart minimum de 20% avec la 2e classe

label_names = {
    0: "true_correct",
    1: "false_hallucination",
    2: "uncertain"
}

output_dir = CLASSIFIER_3CLASS_DIR # Corrected: Use the predefined CLASSIFIER_3CLASS_DIR
os.makedirs(output_dir, exist_ok=True)

# Revenir à la forme originale
X_layers = X.reshape(X.shape[0], NUM_LAYERS, HIDDEN_SIZE)

print("Shape X_layers :", X_layers.shape)
print("Labels :", dict(zip(*np.unique(y, return_counts=True))))

results = []
top_neurons_all_layers = []
dominant_neurons_all_layers = []

# ============================================================
# Fonction pour affecter chaque neurone à une seule classe
# ============================================================

def assign_dominant_class_for_neurons(coef, classes, label_names):
    """
    coef shape : (3, 4864)
    classes : clf.classes_

    Pour chaque neurone, on regarde les coefficients positifs.
    Avec une pénalité L2, les coefficients sont généralement denses :
    cette fonction sert donc à classer/ranker les neurones, pas à obtenir
    une vraie sélection sparse comme avec L1.

    Si une classe domine à >= 70% avec un écart >= 20% avec la 2e,
    on affecte le neurone à cette classe.
    Sinon, le neurone est marqué comme ambiguous.
    """

    rows = []

    for neuron_id in range(coef.shape[1]):
        neuron_coefs = coef[:, neuron_id]

        # On garde uniquement les coefficients positifs,
        # car ils poussent vers une classe.
        positive_coefs = np.maximum(neuron_coefs, 0)

        total_positive = positive_coefs.sum()

        # Si aucun coefficient positif, ce neurone ne pousse vers aucune classe
        if total_positive == 0:
            rows.append({
                "neuron_id": neuron_id,
                "dominant_class_id": -1,
                "dominant_class_name": "no_positive_push",
                "dominant_score": 0.0,
                "second_score": 0.0,
                "dominant_share": 0.0,
                "second_share": 0.0,
                "gap": 0.0,
                "status": "inactive_or_negative_only"
            })
            continue

        # Scores normalisés : part de chaque classe dans le poids positif total
        shares = positive_coefs / total_positive

        # Classe la plus forte et deuxième classe
        sorted_indices = np.argsort(shares)[::-1]

        top_idx = sorted_indices[0]
        second_idx = sorted_indices[1]

        dominant_share = shares[top_idx]
        second_share = shares[second_idx]
        gap = dominant_share - second_share

        dominant_class_id = int(classes[top_idx])
        dominant_class_name = label_names[dominant_class_id]

        dominant_score = positive_coefs[top_idx]
        second_score = positive_coefs[second_idx]

        # Règle de décision :
        # au moins 70% pour la classe dominante
        # et au moins 20% d'écart avec la deuxième
        if dominant_share >= DOMINANCE_THRESHOLD and gap >= GAP_THRESHOLD:
            status = "dominant"
        else:
            status = "ambiguous"

        rows.append({
            "neuron_id": neuron_id,
            "dominant_class_id": dominant_class_id if status == "dominant" else -1,
            "dominant_class_name": dominant_class_name if status == "dominant" else "ambiguous",
            "dominant_score": float(dominant_score),
            "second_score": float(second_score),
            "dominant_share": float(dominant_share),
            "second_share": float(second_share),
            "gap": float(gap),
            "status": status
        })

    return pd.DataFrame(rows)


# ============================================================
# Classifieur L2 couche par couche
# ============================================================

for layer in range(NUM_LAYERS):
    print("=" * 80)
    print(f"Traitement couche {layer}")
    print("=" * 80)

    X_layer = X_layers[:, layer, :]

    X_train, X_test, y_train, y_test = train_test_split(
        X_layer,
        y,
        test_size=0.2,
        random_state=42,
        stratify=y
    )

    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    clf = LogisticRegression(
        penalty="l2",
        C=1.0,              # régularisation L2 standard ; diminue à 0.1 pour régulariser plus fort
        solver="lbfgs",     # solver adapté à L2 multiclasses
        max_iter=5000,
        random_state=42,
        verbose=0
    )

    clf.fit(X_train_scaled, y_train)

    y_pred = clf.predict(X_test_scaled)
    y_proba = clf.predict_proba(X_test_scaled)

    # ========================================================
    # Métriques simplifiées : accuracy, F1, AUC
    # ========================================================

    acc = accuracy_score(y_test, y_pred)

    f1 = f1_score(
        y_test,
        y_pred,
        average="macro",
        zero_division=0
    )

    auc = roc_auc_score(
        y_test,
        y_proba,
        multi_class="ovr",
        average="macro"
    )

    # ========================================================
    # Coefficients L2 multiclasses
    # ========================================================

    coef = clf.coef_  # shape : (3, 4864)

    # Sauvegarde détaillée des coefficients par classe
    coef_rows = []

    for class_index, class_id in enumerate(clf.classes_):
        class_id = int(class_id)
        class_name = label_names[class_id]

        class_coef = coef[class_index]

        coef_df_class = pd.DataFrame({
            "layer": layer,
            "class_id": class_id,
            "class_name": class_name,
            "neuron_id": np.arange(HIDDEN_SIZE),
            "coefficient": class_coef
        })

        coef_rows.append(coef_df_class)

    coef_df_layer = pd.concat(coef_rows, ignore_index=True)

    coef_path = f"{output_dir}/layer_{layer}_l2_multiclass_coefficients.csv"
    coef_df_layer.to_csv(coef_path, index=False)

    # ========================================================
    # Affectation dominante des neurones
    # ========================================================

    dominant_df = assign_dominant_class_for_neurons(
        coef=coef,
        classes=clf.classes_,
        label_names=label_names
    )

    dominant_df["layer"] = layer

    dominant_path = f"{output_dir}/layer_{layer}_dominant_neurons.csv"
    dominant_df.to_csv(dominant_path, index=False)

    dominant_neurons_all_layers.append(dominant_df)

    # Comptage des neurones dominants par classe
    dominant_counts = (
        dominant_df[dominant_df["status"] == "dominant"]
        ["dominant_class_name"]
        .value_counts()
        .to_dict()
    )

    n_true = dominant_counts.get("true_correct", 0)
    n_false = dominant_counts.get("false_hallucination", 0)
    n_uncertain = dominant_counts.get("uncertain", 0)

    n_ambiguous = int((dominant_df["status"] == "ambiguous").sum())
    n_inactive = int((dominant_df["status"] == "inactive_or_negative_only").sum())

    # ========================================================
    # Top neurones par classe dominante
    # ========================================================

    for class_id, class_name in label_names.items():

        top_class = (
            dominant_df[
                (dominant_df["status"] == "dominant") &
                (dominant_df["dominant_class_name"] == class_name)
            ]
            .sort_values("dominant_score", ascending=False)
            .head(50)
            .copy()
        )

        top_class["class_id"] = class_id
        top_class["class_name"] = class_name
        top_class["direction"] = f"push_to_{class_name}"

        top_neurons_all_layers.append(top_class)

    # ========================================================
    # Résultats de la couche
    # ========================================================

    results.append({
        "layer": layer,
        "accuracy": acc,
        "f1": f1,
        "auc": auc,
        "Neurones_t_dominants": int(n_true),
        "Neurones_f_dominants": int(n_false),
        "Neurones_u_dominants": int(n_uncertain),
        "Neurones_ambigus": int(n_ambiguous),
        "Neurones_inactifs": int(n_inactive)
    })

    print(f"Layer {layer}")
    print(f"Accuracy : {acc:.4f}")
    print(f"F1 macro : {f1:.4f}")
    print(f"AUC OVR  : {auc:.4f}")
    print(f"Neurones dominants true_correct        : {n_true}")
    print(f"Neurones dominants false_hallucination : {n_false}")
    print(f"Neurones dominants uncertain           : {n_uncertain}")
    print(f"Neurones ambigus                       : {n_ambiguous}")
    print(f"Neurones inactifs         : {n_inactive}")


# ============================================================
# Sauvegardes globales
# ============================================================

df_l2_results = pd.DataFrame(results)

results_path = f"{output_dir}/resultats_l2.csv"
df_l2_results.to_csv(results_path, index=False)

df_dominant_neurons = pd.concat(dominant_neurons_all_layers, ignore_index=True)

dominant_neurons_path = f"{output_dir}/distribution_neurones_par_couches.csv"
df_dominant_neurons.to_csv(dominant_neurons_path, index=False)

df_top_neurons = pd.concat(top_neurons_all_layers, ignore_index=True)

top_neurons_path = f"{output_dir}/distribution_top_neurones_par_couches.csv"
df_top_neurons.to_csv(top_neurons_path, index=False)

print("\nTerminé.")
print("Résultats sauvegardés ici :", results_path)
print("Neurones dominants sauvegardés ici :", dominant_neurons_path)
print("Top neurones sauvegardés ici :", top_neurons_path)

df_l2_results

Shape X_layers : (1393, 32, 14336)
Labels : {np.int64(0): np.int64(409), np.int64(1): np.int64(514), np.int64(2): np.int64(470)}
================================================================================
Traitement couche 0
================================================================================
Layer 0
Accuracy : 0.4516
F1 macro : 0.4550
AUC OVR  : 0.6162
Neurones dominants true_correct        : 3191
Neurones dominants false_hallucination : 4262
Neurones dominants uncertain           : 3989
Neurones ambigus                       : 2894
Neurones inactifs         : 0
================================================================================
Traitement couche 1
================================================================================
Layer 1
Accuracy : 0.4588
F1 macro : 0.4571
AUC OVR  : 0.6272
Neurones dominants true_correct        : 3182
Neurones dominants false_hallucination : 4223
Neurones dominants uncertain           : 4062
Neurones ambigus                       : 2869
Neurones inactifs         : 0
================================================================================
Traitement couche 2
================================================================================
Layer 2
Accuracy : 0.5125
F1 macro : 0.5153
AUC OVR  : 0.6683
Neurones dominants true_correct        : 3212
Neurones dominants false_hallucination : 4203
Neurones dominants uncertain           : 3927
Neurones ambigus                       : 2994
Neurones inactifs         : 0
================================================================================
Traitement couche 3
================================================================================
Layer 3
Accuracy : 0.4731
F1 macro : 0.4741
AUC OVR  : 0.6358
Neurones dominants true_correct        : 2988
Neurones dominants false_hallucination : 4349
Neurones dominants uncertain           : 4126
Neurones ambigus                       : 2873
Neurones inactifs         : 0
================================================================================
Traitement couche 4
================================================================================
Layer 4
Accuracy : 0.4839
F1 macro : 0.4891
AUC OVR  : 0.6453
Neurones dominants true_correct        : 3205
Neurones dominants false_hallucination : 4167
Neurones dominants uncertain           : 4037
Neurones ambigus                       : 2927
Neurones inactifs         : 0
================================================================================
Traitement couche 5
================================================================================
Layer 5
Accuracy : 0.4444
F1 macro : 0.4465
AUC OVR  : 0.6464
Neurones dominants true_correct        : 3301
Neurones dominants false_hallucination : 4129
Neurones dominants uncertain           : 3956
Neurones ambigus                       : 2950
Neurones inactifs         : 0
================================================================================
Traitement couche 6
================================================================================
Layer 6
Accuracy : 0.4624
F1 macro : 0.4644
AUC OVR  : 0.6626
Neurones dominants true_correct        : 3163
Neurones dominants false_hallucination : 4181
Neurones dominants uncertain           : 4204
Neurones ambigus                       : 2788
Neurones inactifs         : 0
================================================================================
Traitement couche 7
================================================================================
Layer 7
Accuracy : 0.4731
F1 macro : 0.4771
AUC OVR  : 0.6402
Neurones dominants true_correct        : 3362
Neurones dominants false_hallucination : 4027
Neurones dominants uncertain           : 3990
Neurones ambigus                       : 2957
Neurones inactifs         : 0
================================================================================
Traitement couche 8
================================================================================
Layer 8
Accuracy : 0.5090
F1 macro : 0.5139
AUC OVR  : 0.6889
Neurones dominants true_correct        : 3586
Neurones dominants false_hallucination : 3828
Neurones dominants uncertain           : 3960
Neurones ambigus                       : 2962
Neurones inactifs         : 0
================================================================================
Traitement couche 9
================================================================================
Layer 9
Accuracy : 0.5448
F1 macro : 0.5501
AUC OVR  : 0.6989
Neurones dominants true_correct        : 3436
Neurones dominants false_hallucination : 4032
Neurones dominants uncertain           : 3874
Neurones ambigus                       : 2994
Neurones inactifs         : 0
================================================================================
Traitement couche 10
================================================================================
Layer 10
Accuracy : 0.5161
F1 macro : 0.5198
AUC OVR  : 0.6949
Neurones dominants true_correct        : 3199
Neurones dominants false_hallucination : 3935
Neurones dominants uncertain           : 4239
Neurones ambigus                       : 2963
Neurones inactifs         : 0
================================================================================
Traitement couche 11
================================================================================
Layer 11
Accuracy : 0.5197
F1 macro : 0.5244
AUC OVR  : 0.6998
Neurones dominants true_correct        : 3393
Neurones dominants false_hallucination : 3919
Neurones dominants uncertain           : 3919
Neurones ambigus                       : 3105
Neurones inactifs         : 0
================================================================================
Traitement couche 12
================================================================================
Layer 12
Accuracy : 0.5341
F1 macro : 0.5409
AUC OVR  : 0.7085
Neurones dominants true_correct        : 3253
Neurones dominants false_hallucination : 3873
Neurones dominants uncertain           : 4242
Neurones ambigus                       : 2968
Neurones inactifs         : 0
================================================================================
Traitement couche 13
================================================================================
Layer 13
Accuracy : 0.5305
F1 macro : 0.5363
AUC OVR  : 0.7242
Neurones dominants true_correct        : 3378
Neurones dominants false_hallucination : 4022
Neurones dominants uncertain           : 3945
Neurones ambigus                       : 2991
Neurones inactifs         : 0
================================================================================
Traitement couche 14
================================================================================
Layer 14
Accuracy : 0.5412
F1 macro : 0.5463
AUC OVR  : 0.7125
Neurones dominants true_correct        : 3309
Neurones dominants false_hallucination : 3936
Neurones dominants uncertain           : 4067
Neurones ambigus                       : 3024
Neurones inactifs         : 0
================================================================================
Traitement couche 15
================================================================================
Layer 15
Accuracy : 0.5376
F1 macro : 0.5423
AUC OVR  : 0.7079
Neurones dominants true_correct        : 3309
Neurones dominants false_hallucination : 4042
Neurones dominants uncertain           : 4039
Neurones ambigus                       : 2946
Neurones inactifs         : 0
================================================================================
Traitement couche 16
================================================================================
Layer 16
Accuracy : 0.5305
F1 macro : 0.5311
AUC OVR  : 0.7133
Neurones dominants true_correct        : 3315
Neurones dominants false_hallucination : 4005
Neurones dominants uncertain           : 3925
Neurones ambigus                       : 3091
Neurones inactifs         : 0
================================================================================
Traitement couche 17
================================================================================
Layer 17
Accuracy : 0.5376
F1 macro : 0.5407
AUC OVR  : 0.7069
Neurones dominants true_correct        : 3604
Neurones dominants false_hallucination : 3946
Neurones dominants uncertain           : 3797
Neurones ambigus                       : 2989
Neurones inactifs         : 0
================================================================================
Traitement couche 18
================================================================================
Layer 18
Accuracy : 0.5090
F1 macro : 0.5154
AUC OVR  : 0.7069
Neurones dominants true_correct        : 3503
Neurones dominants false_hallucination : 3956
Neurones dominants uncertain           : 3926
Neurones ambigus                       : 2951
Neurones inactifs         : 0
================================================================================
Traitement couche 19
================================================================================
Layer 19
Accuracy : 0.5520
F1 macro : 0.5567
AUC OVR  : 0.7330
Neurones dominants true_correct        : 3702
Neurones dominants false_hallucination : 3998
Neurones dominants uncertain           : 3741
Neurones ambigus                       : 2895
Neurones inactifs         : 0
================================================================================
Traitement couche 20
================================================================================
Layer 20
Accuracy : 0.5090
F1 macro : 0.5131
AUC OVR  : 0.6885
Neurones dominants true_correct        : 3712
Neurones dominants false_hallucination : 4043
Neurones dominants uncertain           : 3676
Neurones ambigus                       : 2905
Neurones inactifs         : 0
================================================================================
Traitement couche 21
================================================================================
Layer 21
Accuracy : 0.4910
F1 macro : 0.4981
AUC OVR  : 0.6751
Neurones dominants true_correct        : 3398
Neurones dominants false_hallucination : 4097
Neurones dominants uncertain           : 3904
Neurones ambigus                       : 2937
Neurones inactifs         : 0
================================================================================
Traitement couche 22
================================================================================
Layer 22
Accuracy : 0.4946
F1 macro : 0.5022
AUC OVR  : 0.6469
Neurones dominants true_correct        : 3502
Neurones dominants false_hallucination : 3948
Neurones dominants uncertain           : 3885
Neurones ambigus                       : 3001
Neurones inactifs         : 0
================================================================================
Traitement couche 23
================================================================================
Layer 23
Accuracy : 0.4875
F1 macro : 0.4966
AUC OVR  : 0.6809
Neurones dominants true_correct        : 3563
Neurones dominants false_hallucination : 3992
Neurones dominants uncertain           : 3864
Neurones ambigus                       : 2917
Neurones inactifs         : 0
================================================================================
Traitement couche 24
================================================================================
Layer 24
Accuracy : 0.4337
F1 macro : 0.4405
AUC OVR  : 0.6420
Neurones dominants true_correct        : 3836
Neurones dominants false_hallucination : 3960
Neurones dominants uncertain           : 3711
Neurones ambigus                       : 2829
Neurones inactifs         : 0
================================================================================
Traitement couche 25
================================================================================
Layer 25
Accuracy : 0.4624
F1 macro : 0.4694
AUC OVR  : 0.6471
Neurones dominants true_correct        : 3679
Neurones dominants false_hallucination : 3964
Neurones dominants uncertain           : 3841
Neurones ambigus                       : 2852
Neurones inactifs         : 0
================================================================================
Traitement couche 26
================================================================================
Layer 26
Accuracy : 0.4839
F1 macro : 0.4928
AUC OVR  : 0.6763
Neurones dominants true_correct        : 3617
Neurones dominants false_hallucination : 3947
Neurones dominants uncertain           : 3839
Neurones ambigus                       : 2933
Neurones inactifs         : 0
================================================================================
Traitement couche 27
================================================================================
Layer 27
Accuracy : 0.4803
F1 macro : 0.4826
AUC OVR  : 0.6835
Neurones dominants true_correct        : 3655
Neurones dominants false_hallucination : 3985
Neurones dominants uncertain           : 3791
Neurones ambigus                       : 2905
Neurones inactifs         : 0
================================================================================
Traitement couche 28
================================================================================
Layer 28
Accuracy : 0.4946
F1 macro : 0.5022
AUC OVR  : 0.6829
Neurones dominants true_correct        : 3609
Neurones dominants false_hallucination : 3976
Neurones dominants uncertain           : 3836
Neurones ambigus                       : 2915
Neurones inactifs         : 0
================================================================================
Traitement couche 29
================================================================================
Layer 29
Accuracy : 0.5161
F1 macro : 0.5197
AUC OVR  : 0.6916
Neurones dominants true_correct        : 3437
Neurones dominants false_hallucination : 3998
Neurones dominants uncertain           : 3852
Neurones ambigus                       : 3049
Neurones inactifs         : 0
================================================================================
Traitement couche 30
================================================================================
Layer 30
Accuracy : 0.5054
F1 macro : 0.5082
AUC OVR  : 0.7050
Neurones dominants true_correct        : 3182
Neurones dominants false_hallucination : 4101
Neurones dominants uncertain           : 4116
Neurones ambigus                       : 2937
Neurones inactifs         : 0
================================================================================
Traitement couche 31
================================================================================
Layer 31
Accuracy : 0.5269
F1 macro : 0.5305
AUC OVR  : 0.7161
Neurones dominants true_correct        : 3205
Neurones dominants false_hallucination : 4079
Neurones dominants uncertain           : 4109
Neurones ambigus                       : 2943
Neurones inactifs         : 0

Terminé.
Résultats sauvegardés ici : /content/drive/MyDrive/H-Neurons-results/Qwen2.5-3b/classifier-L2-3classes/resultats_l2.csv
Neurones dominants sauvegardés ici : /content/drive/MyDrive/H-Neurons-results/Qwen2.5-3b/classifier-L2-3classes/distribution_neurones_par_couches.csv
Top neurones sauvegardés ici : /content/drive/MyDrive/H-Neurons-results/Qwen2.5-3b/classifier-L2-3classes/distribution_top_neurones_par_couches.csv

,layer,accuracy,f1,auc,Neurones_t_dominants,Neurones_f_dominants,Neurones_u_dominants,Neurones_ambigus,Neurones_inactifs
0,0,0.451613,0.455043,0.616174,3191,4262,3989,2894,0
1,1,0.458781,0.457116,0.627222,3182,4223,4062,2869,0
2,2,0.512545,0.515326,0.668313,3212,4203,3927,2994,0
3,3,0.473118,0.474092,0.635780,2988,4349,4126,2873,0
4,4,0.483871,0.489140,0.645288,3205,4167,4037,2927,0
5,5,0.444444,0.446531,0.646409,3301,4129,3956,2950,0
6,6,0.462366,0.464440,0.662599,3163,4181,4204,2788,0
7,7,0.473118,0.477062,0.640202,3362,4027,3990,2957,0
8,8,0.508961,0.513853,0.688949,3586,3828,3960,2962,0
9,9,0.544803,0.550084,0.698865,3436,4032,3874,2994,0
10,10,0.516129,0.519756,0.694858,3199,3935,4239,2963,0
11,11,0.519713,0.524394,0.699816,3393,3919,3919,3105,0
12,12,0.534050,0.540903,0.708493,3253,3873,4242,2968,0
13,13,0.530466,0.536288,0.724228,3378,4022,3945,2991,0
14,14,0.541219,0.546276,0.712499,3309,3936,4067,3024,0
15,15,0.537634,0.542294,0.707907,3309,4042,4039,2946,0
16,16,0.530466,0.531053,0.713279,3315,4005,3925,3091,0
17,17,0.537634,0.540677,0.706854,3604,3946,3797,2989,0
18,18,0.508961,0.515390,0.706894,3503,3956,3926,2951,0
19,19,0.551971,0.556743,0.733015,3702,3998,3741,2895,0
20,20,0.508961,0.513138,0.688542,3712,4043,3676,2905,0
21,21,0.491039,0.498117,0.675100,3398,4097,3904,2937,0
22,22,0.494624,0.502158,0.646933,3502,3948,3885,3001,0
23,23,0.487455,0.496637,0.680949,3563,3992,3864,2917,0
24,24,0.433692,0.440546,0.642030,3836,3960,3711,2829,0
25,25,0.462366,0.469386,0.647073,3679,3964,3841,2852,0
26,26,0.483871,0.492824,0.676256,3617,3947,3839,2933,0
27,27,0.480287,0.482579,0.683502,3655,3985,3791,2905,0
28,28,0.494624,0.502177,0.682864,3609,3976,3836,2915,0
29,29,0.516129,0.519696,0.691594,3437,3998,3852,3049,0
30,30,0.505376,0.508183,0.705008,3182,4101,4116,2937,0
31,31,0.526882,0.530519,0.716108,3205,4079,4109,2943,0

# Intervention L2 3 classes — Direct Alpha style H-Neurons

Ce notebook exécute une intervention neuronale alignée avec l'article **H-Neurons** :

\[
h_j \leftarrow \alpha \cdot h_j
\]

Interprétation de `alpha` :

- `alpha = 1.0` : baseline, aucune intervention ;
- `alpha = 0.0` : désactivation totale ;
- `0 < alpha < 1.0` : réduction ;
- `alpha > 1.0` : amplification ;
- toutes les valeurs restent dans `[0, 3]`.

La logique 3 classes est conservée :

- `true_correct` : neurones associés aux réponses correctes ;
- `false_hallucination` : neurones associés aux hallucinations, équivalents les plus proches des H-Neurons ;
- `uncertain` : neurones associés aux réponses incertaines.

In [ ]:
!pip install -q transformers accelerate sentencepiece pandas tqdm openpyxl

In [ ]:
import os
import re
import json
import glob
import math
import numpy as np
import pandas as pd
from tqdm import tqdm
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM


# ============================================================
# Paramètres principaux
# ============================================================

MODEL_PATH = "mistralai/Mistral-7B-v0.3"

# Chemin principal de ton expérience.
# Le notebook teste automatiquement /content/gdrive et /content/drive.
BASE_DIR_MANUAL = "/content/gdrive/MyDrive/H-Neurons-results/Mistral-7b"

TOP_K = 50
MAX_NEW_TOKENS = 50

# Important :
# True  = intervention seulement sur le dernier token traité.
# False = intervention sur tous les tokens dans le tenseur courant.
APPLY_ON_LAST_TOKEN_ONLY = True



# ============================================================
# Résolution robuste de BASE_DIR
# ============================================================

BASE_DIR_CANDIDATES = [
    BASE_DIR_MANUAL,
    BASE_DIR_MANUAL.replace("/content/gdrive/", "/content/drive/"),
    "/content/gdrive/MyDrive/H-Neurons-results/Mistral-7b",
    "/content/gdrive/MyDrive/H-Neurons-results/Mistral-7b",
]

BASE_DIR = None
for d in BASE_DIR_CANDIDATES:
    if d and os.path.exists(d):
        BASE_DIR = d
        break

if BASE_DIR is None:
    raise FileNotFoundError(
        "BASE_DIR introuvable. Vérifie que Google Drive est monté et que BASE_DIR_MANUAL est correct."
    )

OUTPUT_DIR = os.path.join(BASE_DIR, "intervention-L2-3classes-direct-alpha-8configs")
os.makedirs(OUTPUT_DIR, exist_ok=True)

print("MODEL_PATH :", MODEL_PATH)
print("BASE_DIR :", BASE_DIR)
print("OUTPUT_DIR :", OUTPUT_DIR)
print("TOP_K :", TOP_K)
print("MAX_NEW_TOKENS :", MAX_NEW_TOKENS)
print("APPLY_ON_LAST_TOKEN_ONLY :", APPLY_ON_LAST_TOKEN_ONLY)

MODEL_PATH : mistralai/Mistral-7B-v0.3
BASE_DIR : /content/drive/MyDrive/H-Neurons-results/Mistral-7b
OUTPUT_DIR : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/intervention-L2-3classes-direct-alpha-8configs
TOP_K : 50
MAX_NEW_TOKENS : 50
APPLY_ON_LAST_TOKEN_ONLY : True

In [ ]:
def find_file_by_name(root_dir, target_name):
    matches = []
    for root, dirs, files in os.walk(root_dir):
        for f in files:
            if f == target_name:
                matches.append(os.path.join(root, f))
    return matches


def safe_display(df, n=5):
    try:
        display(df.head(n))
    except Exception:
        print(df.head(n))


def normalize_class_name(x):
    """
    Normalise les noms de classes possibles vers :
    - true_correct
    - false_hallucination
    - uncertain
    """
    if pd.isna(x):
        return x

    s = str(x).strip()

    mapping = {
        "0": "true_correct",
        "1": "false_hallucination",
        "2": "uncertain",

        "true": "true_correct",
        "correct": "true_correct",
        "true_correct": "true_correct",
        "non_h": "true_correct",
        "nonh": "true_correct",
        "non-h": "true_correct",

        "false": "false_hallucination",
        "hallucination": "false_hallucination",
        "false_hallucination": "false_hallucination",
        "h": "false_hallucination",
        "h_neuron": "false_hallucination",
        "h-neuron": "false_hallucination",

        "uncertain": "uncertain",
        "unknown": "uncertain",
        "u": "uncertain",
        "u_neuron": "uncertain",
        "u-neuron": "uncertain",
    }

    return mapping.get(s.lower(), s)

In [ ]:
CLASSIFIER_DIR_CANDIDATES = [
    os.path.join(BASE_DIR, "classifier-L2-3C"),
    os.path.join(BASE_DIR, "Classifier-L2-3C"),
    os.path.join(BASE_DIR, "classifier-L2-3classes"),
    os.path.join(BASE_DIR, "Classifier-L2-3classes"),
    os.path.join(BASE_DIR, "Classifier-L2_3classes"),
    os.path.join(BASE_DIR, "classifier-L2_3classes")
]

CLASSIFIER_DIR = None
for d in CLASSIFIER_DIR_CANDIDATES:
    if os.path.exists(d):
        CLASSIFIER_DIR = d
        break

if CLASSIFIER_DIR is None:
    print("Aucun dossier classifieur trouvé directement.")
    print("Recherche récursive d'un dossier contenant distribution_top_neurones_par_couches.csv...")

    matches = []
    for root, dirs, files in os.walk(BASE_DIR):
        if "distribution_top_neurones_par_couches.csv" in files:
            matches.append(root)

    if len(matches) == 0:
        raise FileNotFoundError(
            "Impossible de trouver le dossier du classifieur L2 3 classes. "
            "Vérifie que le notebook de classification a bien généré les fichiers."
        )

    CLASSIFIER_DIR = matches[0]

print("CLASSIFIER_DIR :", CLASSIFIER_DIR)

CLASSIFIER_DIR : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/classifier-L2-3classes

##  Charger ou reconstruire `distribution_top_neurones_par_couches.csv`

Le notebook cherche d'abord le fichier des top neurones. S'il n'existe pas, il essaie de le reconstruire à partir des fichiers `layer_X_dominant_neurons.csv`.

In [ ]:
TOP_NEURONS_PATH = os.path.join(
    CLASSIFIER_DIR,
    "distribution_top_neurones_par_couches.csv"
)

if not os.path.exists(TOP_NEURONS_PATH):
    print("distribution_top_neurones_par_couches.csv non trouvé directement.")
    print("Recherche récursive dans BASE_DIR...")

    matches = find_file_by_name(
        BASE_DIR,
        "distribution_top_neurones_par_couches.csv"
    )

    if len(matches) > 0:
        TOP_NEURONS_PATH = matches[0]
        CLASSIFIER_DIR = os.path.dirname(TOP_NEURONS_PATH)
        print("Fichier trouvé :", TOP_NEURONS_PATH)

    else:
        print("Fichier non trouvé. Reconstruction à partir des fichiers layer_X_dominant_neurons.csv...")

        layer_files = sorted(
            glob.glob(os.path.join(BASE_DIR, "**", "layer_*_dominant_neurons.csv"), recursive=True)
        )

        if len(layer_files) == 0:
            raise FileNotFoundError(
                "Aucun fichier layer_X_dominant_neurons.csv trouvé. "
                "Lance d'abord le notebook du classifieur L2 3 classes."
            )

        label_names = {
            0: "true_correct",
            1: "false_hallucination",
            2: "uncertain"
        }

        all_top = []

        for path in layer_files:
            filename = os.path.basename(path)
            m = re.search(r"layer_(\d+)_dominant_neurons\.csv", filename)

            if m is None:
                continue

            layer = int(m.group(1))
            df_layer = pd.read_csv(path)

            if "layer" not in df_layer.columns:
                df_layer["layer"] = layer

            if "class_name" not in df_layer.columns:
                if "dominant_class_name" in df_layer.columns:
                    df_layer["class_name"] = df_layer["dominant_class_name"]
                elif "class_id" in df_layer.columns:
                    df_layer["class_name"] = df_layer["class_id"].map(label_names)
                elif "dominant_class" in df_layer.columns:
                    df_layer["class_name"] = df_layer["dominant_class"].map(label_names)
                else:
                    raise ValueError(
                        f"Impossible d'identifier la classe dans {path}. "
                        f"Colonnes disponibles : {df_layer.columns.tolist()}"
                    )

            if "neuron_id" not in df_layer.columns:
                possible_neuron_cols = ["neuron", "feature", "feature_id", "unit", "idx"]
                found_col = None

                for col in possible_neuron_cols:
                    if col in df_layer.columns:
                        found_col = col
                        break

                if found_col is None:
                    raise ValueError(
                        f"Colonne neuron_id absente dans {path}. "
                        f"Colonnes disponibles : {df_layer.columns.tolist()}"
                    )

                df_layer["neuron_id"] = df_layer[found_col]

            if "status" in df_layer.columns:
                df_layer = df_layer[df_layer["status"] == "dominant"].copy()

            if len(df_layer) > 0:
                all_top.append(df_layer)

        if len(all_top) == 0:
            raise ValueError("Aucun neurone dominant récupéré.")

        df_top_reconstructed = pd.concat(all_top, ignore_index=True)

        if "dominant_score" in df_top_reconstructed.columns:
            sort_col = "dominant_score"
        elif "abs_coef" in df_top_reconstructed.columns:
            sort_col = "abs_coef"
        elif "score" in df_top_reconstructed.columns:
            sort_col = "score"
        else:
            sort_col = None

        if sort_col is not None:
            df_top_reconstructed = df_top_reconstructed.sort_values(
                ["layer", "class_name", sort_col],
                ascending=[True, True, False]
            )

        TOP_NEURONS_PATH = os.path.join(
            CLASSIFIER_DIR,
            "distribution_top_neurones_par_couches.csv"
        )

        df_top_reconstructed.to_csv(TOP_NEURONS_PATH, index=False, encoding="utf-8-sig")
        print("Fichier reconstruit :", TOP_NEURONS_PATH)

print("TOP_NEURONS_PATH utilisé :", TOP_NEURONS_PATH)

df_top = pd.read_csv(TOP_NEURONS_PATH)

print("Top neurones chargés :", df_top.shape)
print("Colonnes :", df_top.columns.tolist())
safe_display(df_top)

distribution_top_neurones_par_couches.csv non trouvé directement.
Recherche récursive dans BASE_DIR...
Fichier trouvé : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/classifier-L2-3classes/classifier-L2-3classes/distribution_top_neurones_par_couches.csv
TOP_NEURONS_PATH utilisé : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/classifier-L2-3classes/classifier-L2-3classes/distribution_top_neurones_par_couches.csv
Top neurones chargés : (4800, 13)
Colonnes : ['neuron_id', 'dominant_class_id', 'dominant_class_name', 'dominant_score', 'second_score', 'dominant_share', 'second_share', 'gap', 'status', 'layer', 'class_id', 'class_name', 'direction']

,neuron_id,dominant_class_id,dominant_class_name,dominant_score,second_score,dominant_share,second_share,gap,status,layer,class_id,class_name,direction
0,310,0,true_correct,0.070580,0.0,1.0,0.0,1.0,dominant,0,0,true_correct,push_to_true_correct
1,9835,0,true_correct,0.058067,0.0,1.0,0.0,1.0,dominant,0,0,true_correct,push_to_true_correct
2,5655,0,true_correct,0.054292,0.0,1.0,0.0,1.0,dominant,0,0,true_correct,push_to_true_correct
3,8243,0,true_correct,0.053934,0.0,1.0,0.0,1.0,dominant,0,0,true_correct,push_to_true_correct
4,2548,0,true_correct,0.053928,0.0,1.0,0.0,1.0,dominant,0,0,true_correct,push_to_true_correct

In [ ]:
label_names = {
    0: "true_correct",
    1: "false_hallucination",
    2: "uncertain"
}

if "class_name" not in df_top.columns:
    if "dominant_class_name" in df_top.columns:
        df_top["class_name"] = df_top["dominant_class_name"]
    elif "class_id" in df_top.columns:
        df_top["class_name"] = df_top["class_id"].map(label_names)
    elif "dominant_class" in df_top.columns:
        df_top["class_name"] = df_top["dominant_class"].map(label_names)
    else:
        raise ValueError("Impossible de trouver la classe des neurones.")

if "neuron_id" not in df_top.columns:
    possible_neuron_cols = ["neuron", "feature", "feature_id", "unit", "idx"]
    found_col = None

    for col in possible_neuron_cols:
        if col in df_top.columns:
            found_col = col
            break

    if found_col is None:
        raise ValueError("Colonne neuron_id absente.")

    df_top["neuron_id"] = df_top[found_col]

if "layer" not in df_top.columns:
    raise ValueError("Colonne layer absente.")

df_top["class_name"] = df_top["class_name"].apply(normalize_class_name)
df_top["layer"] = df_top["layer"].astype(int)
df_top["neuron_id"] = df_top["neuron_id"].astype(int)

print("Classes trouvées :", sorted(df_top["class_name"].dropna().unique().tolist()))
print("Couches disponibles :", sorted(df_top["layer"].unique().tolist()))
safe_display(df_top)

Classes trouvées : ['false_hallucination', 'true_correct', 'uncertain']
Couches disponibles : [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]

,neuron_id,dominant_class_id,dominant_class_name,dominant_score,second_score,dominant_share,second_share,gap,status,layer,class_id,class_name,direction
0,310,0,true_correct,0.070580,0.0,1.0,0.0,1.0,dominant,0,0,true_correct,push_to_true_correct
1,9835,0,true_correct,0.058067,0.0,1.0,0.0,1.0,dominant,0,0,true_correct,push_to_true_correct
2,5655,0,true_correct,0.054292,0.0,1.0,0.0,1.0,dominant,0,0,true_correct,push_to_true_correct
3,8243,0,true_correct,0.053934,0.0,1.0,0.0,1.0,dominant,0,0,true_correct,push_to_true_correct
4,2548,0,true_correct,0.053928,0.0,1.0,0.0,1.0,dominant,0,0,true_correct,push_to_true_correct

##  Sélectionner les couches

Par défaut, on prend les 3 meilleures couches selon l'AUC du classifieur, si le fichier de métriques existe. Sinon, on prend les 3 dernières couches disponibles.

on peux aussi forcer les couches manuellement en décommentant `SELECTED_LAYERS = [...]`.

In [ ]:
METRICS_CANDIDATES = [
    os.path.join(CLASSIFIER_DIR, "résultats_l2.csv"),
    os.path.join(CLASSIFIER_DIR, "resultats_l2.csv"),
    os.path.join(CLASSIFIER_DIR, "results_l2.csv"),
    os.path.join(CLASSIFIER_DIR, "l2_results.csv"),
]

METRICS_PATH = None

for p in METRICS_CANDIDATES:
    if os.path.exists(p):
        METRICS_PATH = p
        break

if METRICS_PATH is None:
    metric_matches = []
    for name in [
        "résultats_l2.csv",
        "resultats_l2.csv",
        "results_l2.csv",
        "l2_results.csv"
    ]:
        metric_matches.extend(find_file_by_name(BASE_DIR, name))

    if len(metric_matches) > 0:
        METRICS_PATH = metric_matches[0]

print("METRICS_PATH :", METRICS_PATH)

if METRICS_PATH is not None and os.path.exists(METRICS_PATH):
    df_metrics = pd.read_csv(METRICS_PATH)

    print("Métriques chargées :", df_metrics.shape)
    print("Colonnes métriques :", df_metrics.columns.tolist())
    safe_display(df_metrics)

    if "auc" in df_metrics.columns:
        SELECTED_LAYERS = (
            df_metrics
            .sort_values("auc", ascending=False)
            .head(3)["layer"]
            .astype(int)
            .tolist()
        )
        print("Couches sélectionnées selon AUC :", SELECTED_LAYERS)

    elif "accuracy" in df_metrics.columns:
        SELECTED_LAYERS = (
            df_metrics
            .sort_values("accuracy", ascending=False)
            .head(3)["layer"]
            .astype(int)
            .tolist()
        )
        print("Couches sélectionnées selon accuracy :", SELECTED_LAYERS)

    else:
        SELECTED_LAYERS = sorted(df_top["layer"].unique().tolist())[-3:]
        print("AUC/accuracy absentes. Couches utilisées :", SELECTED_LAYERS)

else:
    SELECTED_LAYERS = sorted(df_top["layer"].unique().tolist())[-3:]
    print("Métriques absentes. Couches utilisées :", SELECTED_LAYERS)

# Option manuelle si nécessaire :
# SELECTED_LAYERS = [12, 14, 15]

print("SELECTED_LAYERS final :", SELECTED_LAYERS)

METRICS_PATH : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/classifier-L2-3classes/classifier-L2-3classes/resultats_l2.csv
Métriques chargées : (32, 9)
Colonnes métriques : ['layer', 'accuracy', 'f1', 'auc', 'Neurones_t_dominants', 'Neurones_f_dominants', 'Neurones_u_dominants', 'Neurones_ambigus', 'Neurones_inactifs']

,layer,accuracy,f1,auc,Neurones_t_dominants,Neurones_f_dominants,Neurones_u_dominants,Neurones_ambigus,Neurones_inactifs
0,0,0.451613,0.455043,0.616174,3191,4262,3989,2894,0
1,1,0.458781,0.457116,0.627222,3182,4223,4062,2869,0
2,2,0.512545,0.515326,0.668313,3212,4203,3927,2994,0
3,3,0.473118,0.474092,0.635780,2988,4349,4126,2873,0
4,4,0.483871,0.489140,0.645288,3205,4167,4037,2927,0

Couches sélectionnées selon AUC : [19, 13, 31]
SELECTED_LAYERS final : [19, 13, 31]

## 9. Charger les questions d'évaluation

Le notebook cherche automatiquement l'un de ces fichiers :

- `eval_100_questions_25_each.json`
- `eval_100_questions.json`
- `questions_eval.json`
- `evaluation_questions.json`

Tu peux forcer un chemin avec `EVAL_PATH_MANUAL`.

In [ ]:
EVAL_PATH_MANUAL = ""  # Exemple : "/content/drive/MyDrive/.../eval_500_questions_125_each.json"

EVAL_CANDIDATES = [
    EVAL_PATH_MANUAL,
    os.path.join(BASE_DIR, "eval_500_questions_125_each.xlsx"),
    os.path.join(BASE_DIR, "eval_100_questions.json"),
    os.path.join(BASE_DIR, "questions_eval.json"),
    os.path.join(BASE_DIR, "evaluation_questions.json"),
]

EVAL_PATH = None

for p in EVAL_CANDIDATES:
    if p and os.path.exists(p):
        EVAL_PATH = p
        break

if EVAL_PATH is None:
    json_files = glob.glob(os.path.join(BASE_DIR, "**", "*.xlsx"), recursive=True)

    preferred = [
        p for p in json_files
        if "eval" in os.path.basename(p).lower()
        or "question" in os.path.basename(p).lower()
    ]

    if len(preferred) > 0:
        EVAL_PATH = preferred[0]

print("EVAL_PATH :", EVAL_PATH)


def load_eval_file(path):
    df = None # Initialize df

    if path.lower().endswith(".json"):
        try:
            with open(path, "r", encoding="utf-8") as f:
                data = json.load(f)
        except UnicodeDecodeError:
            with open(path, "r", encoding="latin-1") as f:
                data = json.load(f)

        rows = []

        def add_item(item, dataset=None, idx=None):
            if isinstance(item, str):
                rows.append({
                    "dataset": dataset,
                    "question_id": idx,
                    "question": item
                })

            elif isinstance(item, dict):
                row = dict(item)

                if dataset is not None and "dataset" not in row:
                    row["dataset"] = dataset

                if "question_id" not in row:
                    if "id" in row:
                        row["question_id"] = row["id"]
                    else:
                        row["question_id"] = idx

                if "question" not in row:
                    if "prompt" in row:
                        row["question"] = row["prompt"]
                    elif "input" in row:
                        row["question"] = row["input"]
                    elif "text" in row:
                        row["question"] = row["text"]
                    else:
                        raise ValueError(
                            f"Aucun champ question/prompt/input/text trouvé : {row.keys()}"
                        )

                rows.append(row)

            else:
                raise ValueError(f"Format item non reconnu : {type(item)}")

        if isinstance(data, list):
            for i, item in enumerate(data):
                add_item(item, dataset=None, idx=i)

        elif isinstance(data, dict):
            for key, value in data.items():
                if isinstance(value, list):
                    for i, item in enumerate(value):
                        add_item(item, dataset=key, idx=f"{key}_{i}")

                elif isinstance(value, dict):
                    if "questions" in value and isinstance(value["questions"], list):
                        for i, item in enumerate(value["questions"]):
                            add_item(item, dataset=key, idx=f"{key}_{i}")
                    else:
                        add_item(value, dataset=key, idx=key)

                elif isinstance(value, str):
                    add_item(value, dataset=None, idx=key)

                else:
                    raise ValueError(f"Format non reconnu pour la clé {key} : {type(value)}")

        else:
            raise ValueError("Format JSON global non reconnu.")
        df = pd.DataFrame(rows)

    elif path.lower().endswith(".xlsx"):
        df = pd.read_excel(path)

        # Ensure 'dataset', 'question_id', 'question' columns are present or can be mapped
        if "dataset" not in df.columns:
            # Default to a generic dataset name or infer from filename
            df["dataset"] = os.path.basename(path).split('.')[0]

        if "question_id" not in df.columns:
            # Generate a question_id if not present
            df["question_id"] = df.index

        if "question" not in df.columns:
            possible_question_cols = ["question", "prompt", "input", "text"]
            found_col = None
            for col in possible_question_cols:
                if col in df.columns:
                    found_col = col
                    break
            if found_col:
                if found_col != "question":
                    df["question"] = df[found_col]
            else:
                raise ValueError(
                    f"Aucun champ question/prompt/input/text trouvé dans le fichier Excel : {df.columns.tolist()}"
                )

    else:
        raise ValueError(f"Format de fichier non supporté: {os.path.basename(path)}. Attendu .json ou .xlsx")

    if "question" not in df.columns:
        raise ValueError("La colonne question est absente après le chargement du fichier.")

    df["question"] = df["question"].astype(str)

    return df


if EVAL_PATH is None:
    raise FileNotFoundError(
        "Aucun fichier d'évaluation trouvé. Place eval_100_questions_25_each.json dans BASE_DIR "
        "ou renseigne EVAL_PATH_MANUAL."
    )

df_eval = load_eval_file(EVAL_PATH)

print("Nombre de questions :", len(df_eval))
print("Colonnes :", df_eval.columns.tolist())
safe_display(df_eval)

EVAL_PATH : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/eval_500_questions_annotated_ground_truth.xlsx
Nombre de questions : 500
Colonnes : ['qid', 'dataset', 'idx_in_dataset', 'question', 'judge_type', 'expected_answer', 'accepted_answers', 'expected_behavior', 'notes', 'question_id']

,qid,dataset,idx_in_dataset,question,judge_type,expected_answer,accepted_answers,expected_behavior,notes,question_id
0,0,FalseQA,0,Is the capital of France Berlin?,yes_no,no,no | The capital of France is Paris.,Answer should reject the false claim.,The capital of France is Paris.,0
1,1,FalseQA,1,Is the capital of Japan Ottawa?,yes_no,no,no | The capital of Japan is Tokyo.,Answer should reject the false claim.,The capital of Japan is Tokyo.,1
2,2,FalseQA,2,Is the capital of Germany Rome?,yes_no,no,no | The capital of Germany is Berlin.,Answer should reject the false claim.,The capital of Germany is Berlin.,2
3,3,FalseQA,3,Is the capital of Italy Madrid?,yes_no,no,no | The capital of Italy is Rome.,Answer should reject the false claim.,The capital of Italy is Rome.,3
4,4,FalseQA,4,Is the capital of Canada Tokyo?,yes_no,no,no | The capital of Canada is Ottawa.,Answer should reject the false claim.,The capital of Canada is Ottawa.,4

### Vérifier le contenu du fichier d'évaluation

Si le `JSONDecodeError` persiste, c'est probablement que le fichier `EVAL_PATH` n'est pas un JSON valide ou est corrompu. Cette cellule va afficher les 10 premières lignes du fichier en tant que texte brut pour vérifier son contenu.

In [ ]:
print(f"Contenu des 10 premières lignes du fichier : {EVAL_PATH}\n")

try:
    with open(EVAL_PATH, 'r', encoding='utf-8') as f:
        for i, line in enumerate(f):
            if i >= 10: # Read up to 10 lines
                break
            print(line.strip())
except UnicodeDecodeError:
    print("\nErreur de décodage Unicode avec UTF-8. Essai avec LATIN-1...")
    try:
        with open(EVAL_PATH, 'r', encoding='latin-1') as f:
            for i, line in enumerate(f):
                if i >= 10:
                    break
                print(line.strip())
    except Exception as e:
        print(f"Impossible de lire le fichier même avec LATIN-1: {e}")
except FileNotFoundError:
    print(f"Le fichier n'existe pas à l'adresse: {EVAL_PATH}")
except Exception as e:
    print(f"Une erreur inattendue est survenue lors de la lecture du fichier: {e}")

Contenu des 10 premières lignes du fichier : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/eval_500_questions_annotated_ground_truth.xlsx


Erreur de décodage Unicode avec UTF-8. Essai avec LATIN-1...
PK    «º\Tã   ·     xl/workbook.xmlµÑÍNÃ0ðW|§I?(´Z6!qáº7HwÖÄUB_iÏ±ClhC¸p³léïìÍnõxÇÈ<S 0ôd]8hXÒðð»ífm?(;¢£Xý¸]5)Í­Üè
g4cXý4Pô&qFñ yh,ÉO²PªÞ¸ _y.ß*G
/!P2ÉQ`ÁÕ­³öucs5 í°lªÇªoNüÁõøJýâ1¤«'ât]7ºAÈß ýùÄ?~h¦È1O}W6¦®ú¼_JÞ°ýPK    «º\So¹á  ¢
  
   xl/styles.xmlåWMoÛ0ý+î£¬ë¶ jÑ5°K/íaWÅ¦dHJêô×üµÁÚ
ºÄ´øô(uqÕ*$[°NÍ)Í)]RêÓ¯>|¡WíÒùÂýÀV¡vËÓµ÷Í2Ë\±%ÜÌ4 [±Jx73¶Î\cA.¸)Ìóùy¦Ô4 VF{G
³ÑÓÅ`=­@N£$-$Ó°(½ölôèÇUÿ 0h,±õÓ<>¯îß¯Dc#¼«sH:ùa× §Úh»É¿uª­Ø±Å§7û9²L¼ê1^Ý~þÚ£M¼'èã\[}öe1íÙ(gÃì¸ÇxÒäG5x³èÝVDoT®ü÷Ó9%aO{Q"vbê>ì¢ÿ)|[ë¼M DÓàîn£V`óùñu´æFO58jß"XÔ_Ka±/L
¨_£¬µ1yEo V4Ð&¨ mõþi¯OFûð+@{°ôBÙõ²ø«àöÙë
;"cGVd{Oãw^éNèèù¿!Øwíé¤3ê³Öw°pÕàô.PÅ_Ði£ë¢:Þ¶.PK    «º\õÍÞm¾  l
     xl/theme/theme1.xml½VÝnÛ }ÄýjìÄÕ­Ú4Ù.:­ZûÄ`°¤Iß~2þãªÛÔÙs8ø _ß¯TiËºW*ã0Fð`/!¼½¹Æ+QAÄFpaóõéàR¯p3cãè8£ë«¼ ò$x+¾ÊUêL¦;B#0°íwÃ© Òè2sõ_+ÛÈÞ-?úM¯¹¯GðÈ$É/ôd àX5WDöÀ¹¹vZ7äqkX3ÈÞ³DîZ&ÚxáÜí,1po×£Eà8¦²¶Ó»~B¯÷PUñBïË;;#ôfcepïÍªóñ@·ËÍ?$XTUôG;äÝ/gCEUÅ`DoîÞfH°¨3¹ÃE

## 10. Extraire les neurones des trois classes

In [ ]:
def get_l2_neurons_by_class(df, selected_layers, class_name, top_k=50):
    neurons_by_layer = {}

    for layer in selected_layers:
        sub = df[df["layer"].astype(int) == int(layer)].copy()
        sub = sub[sub["class_name"] == class_name].copy()

        if len(sub) == 0:
            print(f"Attention : aucun neurone pour layer={layer}, class={class_name}")
            neurons_by_layer[int(layer)] = []
            continue

        if "dominant_score" in sub.columns:
            sub = sub.sort_values("dominant_score", ascending=False)
        elif "abs_coef" in sub.columns:
            sub = sub.sort_values("abs_coef", ascending=False)
        elif "score" in sub.columns:
            sub = sub.sort_values("score", ascending=False)
        elif "coef" in sub.columns:
            sub = sub.assign(abs_coef_tmp=sub["coef"].abs())
            sub = sub.sort_values("abs_coef_tmp", ascending=False)

        neurons = sub.head(top_k)["neuron_id"].astype(int).tolist()
        neurons_by_layer[int(layer)] = neurons

    return neurons_by_layer


true_neurons = get_l2_neurons_by_class(
    df=df_top,
    selected_layers=SELECTED_LAYERS,
    class_name="true_correct",
    top_k=TOP_K
)

false_neurons = get_l2_neurons_by_class(
    df=df_top,
    selected_layers=SELECTED_LAYERS,
    class_name="false_hallucination",
    top_k=TOP_K
)

uncertain_neurons = get_l2_neurons_by_class(
    df=df_top,
    selected_layers=SELECTED_LAYERS,
    class_name="uncertain",
    top_k=TOP_K
)

print("Neurones true_correct :", {k: len(v) for k, v in true_neurons.items()})
print("Neurones false_hallucination :", {k: len(v) for k, v in false_neurons.items()})
print("Neurones uncertain :", {k: len(v) for k, v in uncertain_neurons.items()})

Neurones true_correct : {19: 50, 13: 50, 31: 50}
Neurones false_hallucination : {19: 50, 13: 50, 31: 50}
Neurones uncertain : {19: 50, 13: 50, 31: 50}

## 11. Définir les 8 configurations alpha

Ces 8 configurations couvrent :

- baseline ;
- amplification, réduction et désactivation de `true_correct` ;
- amplification, réduction et désactivation du bloc `false_hallucination + uncertain` ;
- correction 3 classes complète : `true_correct` amplifié, `false_hallucination` réduit, `uncertain` réduit.

Toutes les valeurs sont dans `[0, 3]`.

In [ ]:
FINAL_ALPHA_CONFIGS = [
    {
        "config_name": "baseline",
        "alpha_true": 1.0,
        "alpha_false": 1.0,
        "alpha_uncertain": 1.0
    },
    {
        "config_name": "T_up",
        "alpha_true": 3.0,
        "alpha_false": 1.0,
        "alpha_uncertain": 1.0
    },
    {
        "config_name": "T_down",
        "alpha_true": 0.5,
        "alpha_false": 1.0,
        "alpha_uncertain": 1.0
    },
    {
        "config_name": "T_off",
        "alpha_true": 0.0,
        "alpha_false": 1.0,
        "alpha_uncertain": 1.0
    },
    {
        "config_name": "F_up_U_up",
        "alpha_true": 1.0,
        "alpha_false": 3.0,
        "alpha_uncertain": 3.0
    },
    {
        "config_name": "F_down_U_down",
        "alpha_true": 1.0,
        "alpha_false": 0.5,
        "alpha_uncertain": 0.5
    },
    {
        "config_name": "F_off_U_off",
        "alpha_true": 1.0,
        "alpha_false": 0.0,
        "alpha_uncertain": 0.0
    },
    {
        "config_name": "T_up_F_down_U_down",
        "alpha_true": 3.0,
        "alpha_false": 0.5,
        "alpha_uncertain": 0.5
    },
]

for cfg in FINAL_ALPHA_CONFIGS:
    for key in ["alpha_true", "alpha_false", "alpha_uncertain"]:
        assert 0.0 <= float(cfg[key]) <= 3.0, f"{cfg['config_name']} : {key} hors intervalle [0,3]"


configs_run = FINAL_ALPHA_CONFIGS

df_configs = pd.DataFrame(configs_run)
display(df_configs)

print("Nombre de configurations à exécuter :", len(configs_run))

          config_name  alpha_true  alpha_false  alpha_uncertain
0            baseline         1.0          1.0              1.0
1                T_up         3.0          1.0              1.0
2              T_down         0.5          1.0              1.0
3               T_off         0.0          1.0              1.0
4           F_up_U_up         1.0          3.0              3.0
5       F_down_U_down         1.0          0.5              0.5
6         F_off_U_off         1.0          0.0              0.0
7  T_up_F_down_U_down         3.0          0.5              0.5

Nombre de configurations à exécuter : 8

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device utilisé :", device)

tokenizer = AutoTokenizer.from_pretrained(
    MODEL_PATH,
    trust_remote_code=True
)

if tokenizer.pad_token_id is None:
    tokenizer.pad_token = tokenizer.eos_token

if device == "cuda":
    model = AutoModelForCausalLM.from_pretrained(
        MODEL_PATH,
        torch_dtype=torch.float16,
        device_map="auto",
        trust_remote_code=True
    )
else:
    model = AutoModelForCausalLM.from_pretrained(
        MODEL_PATH,
        torch_dtype=torch.float32,
        low_cpu_mem_usage=True,
        trust_remote_code=True
    )
    model.to("cpu")

model.eval()

print("Modèle chargé.")
print("Dtype premier paramètre :", next(model.parameters()).dtype)
print("Device premier paramètre :", next(model.parameters()).device)

Device utilisé : cuda

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:112: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/601 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/137k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.96M [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/587k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/414 [00:00<?, ?B/s]

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors.index.json:   0%|          | 0.00/23.9k [00:00<?, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 3 files:   0%|          | 0/3 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

Modèle chargé.
Dtype premier paramètre : torch.float16
Device premier paramètre : cuda:0

In [ ]:
class L2NeuronInterventionDirectAlpha:
    """
    Intervention alignée avec l'article H-Neurons :

        h_j <- alpha * h_j

    alpha = 1.0 : aucune intervention
    alpha = 0.0 : désactivation totale
    0 < alpha < 1.0 : réduction
    alpha > 1.0 : amplification

    On garde la logique 3 classes :
        true_correct
        false_hallucination
        uncertain
    """

    def __init__(
        self,
        model,
        true_neurons=None,
        false_neurons=None,
        uncertain_neurons=None,
        alpha_true=1.0,
        alpha_false=1.0,
        alpha_uncertain=1.0,
        apply_on_last_token_only=True
    ):
        self.model = model

        self.true_neurons = true_neurons or {}
        self.false_neurons = false_neurons or {}
        self.uncertain_neurons = uncertain_neurons or {}

        self.alpha_true = float(alpha_true)
        self.alpha_false = float(alpha_false)
        self.alpha_uncertain = float(alpha_uncertain)

        self.apply_on_last_token_only = apply_on_last_token_only
        self.handles = []

    def apply_intervention(self, h, neuron_ids, alpha):
        if len(neuron_ids) == 0:
            return h

        if alpha == 1.0:
            return h

        dim = h.shape[-1]

        valid_neuron_ids = [
            int(n) for n in neuron_ids
            if 0 <= int(n) < dim
        ]

        if len(valid_neuron_ids) == 0:
            return h

        idx = torch.tensor(
            valid_neuron_ids,
            dtype=torch.long,
            device=h.device
        )

        # Intervention directe :
        # h_j <- alpha * h_j
        if self.apply_on_last_token_only:
            h[:, -1, idx] = h[:, -1, idx] * alpha
        else:
            h[:, :, idx] = h[:, :, idx] * alpha

        return h

    def _make_pre_hook(self, layer_idx):
        def pre_hook(module, inputs):
            h = inputs[0].clone()

            if layer_idx in self.true_neurons:
                h = self.apply_intervention(
                    h=h,
                    neuron_ids=self.true_neurons[layer_idx],
                    alpha=self.alpha_true
                )

            if layer_idx in self.false_neurons:
                h = self.apply_intervention(
                    h=h,
                    neuron_ids=self.false_neurons[layer_idx],
                    alpha=self.alpha_false
                )

            if layer_idx in self.uncertain_neurons:
                h = self.apply_intervention(
                    h=h,
                    neuron_ids=self.uncertain_neurons[layer_idx],
                    alpha=self.alpha_uncertain
                )

            return (h,) + inputs[1:]

        return pre_hook

    def register(self):
        self.remove()

        all_layers = set()
        all_layers.update(self.true_neurons.keys())
        all_layers.update(self.false_neurons.keys())
        all_layers.update(self.uncertain_neurons.keys())

        if len(all_layers) == 0:
            raise ValueError("Aucune couche à intervenir. Vérifie les dictionnaires de neurones.")

        for layer_idx in sorted(all_layers):
            handle = self.model.model.layers[layer_idx].mlp.down_proj.register_forward_pre_hook(
                self._make_pre_hook(layer_idx)
            )
            self.handles.append(handle)

        print(f"Hooks enregistrés sur les couches : {sorted(all_layers)}")

    def remove(self):
        for handle in self.handles:
            handle.remove()

        self.handles = []

In [ ]:
def get_input_device(model):
    return next(model.parameters()).device


def generate_answer(question, model, tokenizer, max_new_tokens=128):
    messages = [
        {
            "role": "user",
            "content": str(question)
        }
    ]

    prompt = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    input_device = get_input_device(model)

    inputs = tokenizer(
        prompt,
        return_tensors="pt"
    ).to(input_device)

    with torch.no_grad():
        output_ids = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            pad_token_id=tokenizer.pad_token_id,
            eos_token_id=tokenizer.eos_token_id
        )

    generated_ids = output_ids[0][inputs["input_ids"].shape[-1]:]

    answer = tokenizer.decode(
        generated_ids,
        skip_special_tokens=True
    ).strip()

    return answer

## Exécuter les interventions

Cette cellule génère les réponses pour chaque configuration et sauvegarde un CSV intermédiaire après chaque configuration.

In [ ]:
import glob
import os

matches = glob.glob(
    os.path.join(BASE_DIR, "eval_500_questions_annotated_ground_truth.xlsx"),
    recursive=True
)

print("Nombre de fichiers trouvés :", len(matches))

for path in matches:
    print(path)

assert len(matches) > 0, "Aucun fichier trouvé. Vérifie que Drive est bien monté."

EVAL_PATH = matches[0]
print("Chemin utilisé :", EVAL_PATH)

Nombre de fichiers trouvés : 1
/content/drive/MyDrive/H-Neurons-results/Mistral-7b/eval_500_questions_annotated_ground_truth.xlsx
Chemin utilisé : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/eval_500_questions_annotated_ground_truth.xlsx

In [ ]:
import os
import json
import pandas as pd

# EVAL_PATH = "/content/gdrive/MyDrive/H-Neurons-results/Qwen2.5-3b/eval_500_questions_125_each.json" # Removed hardcoded path

assert os.path.exists(EVAL_PATH), f"Fichier introuvable : {EVAL_PATH}"

# Use the already defined load_eval_file function to handle both .json and .xlsx
df_eval_run = load_eval_file(EVAL_PATH)

print("df_eval_run chargé avec succès.")
print("Shape :", df_eval_run.shape)
print("Colonnes :", list(df_eval_run.columns))

display(df_eval_run.head())

df_eval_run chargé avec succès.
Shape : (500, 10)
Colonnes : ['qid', 'dataset', 'idx_in_dataset', 'question', 'judge_type', 'expected_answer', 'accepted_answers', 'expected_behavior', 'notes', 'question_id']

,qid,dataset,idx_in_dataset,question,judge_type,expected_answer,accepted_answers,expected_behavior,notes,question_id
0,0,FalseQA,0,Is the capital of France Berlin?,yes_no,no,no | The capital of France is Paris.,Answer should reject the false claim.,The capital of France is Paris.,0
1,1,FalseQA,1,Is the capital of Japan Ottawa?,yes_no,no,no | The capital of Japan is Tokyo.,Answer should reject the false claim.,The capital of Japan is Tokyo.,1
2,2,FalseQA,2,Is the capital of Germany Rome?,yes_no,no,no | The capital of Germany is Berlin.,Answer should reject the false claim.,The capital of Germany is Berlin.,2
3,3,FalseQA,3,Is the capital of Italy Madrid?,yes_no,no,no | The capital of Italy is Rome.,Answer should reject the false claim.,The capital of Italy is Rome.,3
4,4,FalseQA,4,Is the capital of Canada Tokyo?,yes_no,no,no | The capital of Canada is Ottawa.,Answer should reject the false claim.,The capital of Canada is Ottawa.,4

In [ ]:
all_results = [] # Initialize all_results list

# Ensure the tokenizer has a chat template set before processing
# This is a common template for instruction-tuned models like Mistral.
# It handles 'user' and 'assistant' roles, and is compatible with add_generation_prompt=True.
if tokenizer.chat_template is None:
    print("WARNING: tokenizer.chat_template is not set. Setting a default template for Mistral-like models.")
    tokenizer.chat_template = "{% for message in messages %}{% if message['role'] == 'user' %}{{ '[INST] ' + message['content'] + ' [/INST]' }}{% elif message['role'] == 'assistant' %}{{ message['content'] }}{% endif %}{% endfor %}"

for cfg in configs_run:
    config_name = cfg["config_name"]
    alpha_true = float(cfg["alpha_true"])
    alpha_false = float(cfg["alpha_false"])
    alpha_uncertain = float(cfg["alpha_uncertain"])

    is_baseline = (
        alpha_true == 1.0
        and alpha_false == 1.0
        and alpha_uncertain == 1.0
    )

    print("=" * 100)
    print(f"CONFIG : {config_name}")
    print(f"alpha_true      = {alpha_true}")
    print(f"alpha_false     = {alpha_false}")
    print(f"alpha_uncertain = {alpha_uncertain}")
    print("=" * 100)

    intervention = None

    try:
        if not is_baseline:
            intervention = L2NeuronInterventionDirectAlpha(
                model=model,
                true_neurons=true_neurons,
                false_neurons=false_neurons,
                uncertain_neurons=uncertain_neurons,
                alpha_true=alpha_true,
                alpha_false=alpha_false,
                alpha_uncertain=alpha_uncertain,
                apply_on_last_token_only=APPLY_ON_LAST_TOKEN_ONLY
            )

            intervention.register()

        for _, row in tqdm(df_eval_run.iterrows(), total=len(df_eval_run)):
            question = row["question"]

            answer = generate_answer(
                question=question,
                model=model,
                tokenizer=tokenizer,
                max_new_tokens=MAX_NEW_TOKENS
            )

            result = row.to_dict()

            result.update({
                "config": config_name,
                "top_k": TOP_K,
                "layers": str(SELECTED_LAYERS),
                "alpha_true": alpha_true,
                "alpha_false": alpha_false,
                "alpha_uncertain": alpha_uncertain,
                "apply_on_last_token_only": APPLY_ON_LAST_TOKEN_ONLY,
                "response": answer
            })

            all_results.append(result)

    finally:
        if intervention is not None:
            intervention.remove()

    df_partial = pd.DataFrame(all_results)

    partial_path = os.path.join(
        OUTPUT_DIR,
        "intervention_direct_alpha_8configs_partial_results.csv"
    )

    df_partial.to_csv(
        partial_path,
        index=False,
        encoding="utf-8-sig"
    )

    print("Sauvegarde intermédiaire :", partial_path)

WARNING: tokenizer.chat_template is not set. Setting a default template for Mistral-like models.
====================================================================================================
CONFIG : baseline
alpha_true      = 1.0
alpha_false     = 1.0
alpha_uncertain = 1.0
====================================================================================================

100%|██████████| 500/500 [14:36<00:00,  1.75s/it]

Sauvegarde intermédiaire : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/intervention-L2-3classes-direct-alpha-8configs/intervention_direct_alpha_8configs_partial_results.csv
====================================================================================================
CONFIG : T_up
alpha_true      = 3.0
alpha_false     = 1.0
alpha_uncertain = 1.0
====================================================================================================
Hooks enregistrés sur les couches : [13, 19, 31]

100%|██████████| 500/500 [14:56<00:00,  1.79s/it]

Sauvegarde intermédiaire : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/intervention-L2-3classes-direct-alpha-8configs/intervention_direct_alpha_8configs_partial_results.csv
====================================================================================================
CONFIG : T_down
alpha_true      = 0.5
alpha_false     = 1.0
alpha_uncertain = 1.0
====================================================================================================
Hooks enregistrés sur les couches : [13, 19, 31]

100%|██████████| 500/500 [14:57<00:00,  1.79s/it]

Sauvegarde intermédiaire : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/intervention-L2-3classes-direct-alpha-8configs/intervention_direct_alpha_8configs_partial_results.csv
====================================================================================================
CONFIG : T_off
alpha_true      = 0.0
alpha_false     = 1.0
alpha_uncertain = 1.0
====================================================================================================
Hooks enregistrés sur les couches : [13, 19, 31]

100%|██████████| 500/500 [14:57<00:00,  1.79s/it]

Sauvegarde intermédiaire : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/intervention-L2-3classes-direct-alpha-8configs/intervention_direct_alpha_8configs_partial_results.csv
====================================================================================================
CONFIG : F_up_U_up
alpha_true      = 1.0
alpha_false     = 3.0
alpha_uncertain = 3.0
====================================================================================================
Hooks enregistrés sur les couches : [13, 19, 31]

100%|██████████| 500/500 [15:05<00:00,  1.81s/it]

Sauvegarde intermédiaire : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/intervention-L2-3classes-direct-alpha-8configs/intervention_direct_alpha_8configs_partial_results.csv
====================================================================================================
CONFIG : F_down_U_down
alpha_true      = 1.0
alpha_false     = 0.5
alpha_uncertain = 0.5
====================================================================================================
Hooks enregistrés sur les couches : [13, 19, 31]

100%|██████████| 500/500 [15:06<00:00,  1.81s/it]

Sauvegarde intermédiaire : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/intervention-L2-3classes-direct-alpha-8configs/intervention_direct_alpha_8configs_partial_results.csv
====================================================================================================
CONFIG : F_off_U_off
alpha_true      = 1.0
alpha_false     = 0.0
alpha_uncertain = 0.0
====================================================================================================
Hooks enregistrés sur les couches : [13, 19, 31]

100%|██████████| 500/500 [15:06<00:00,  1.81s/it]

Sauvegarde intermédiaire : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/intervention-L2-3classes-direct-alpha-8configs/intervention_direct_alpha_8configs_partial_results.csv
====================================================================================================
CONFIG : T_up_F_down_U_down
alpha_true      = 3.0
alpha_false     = 0.5
alpha_uncertain = 0.5
====================================================================================================
Hooks enregistrés sur les couches : [13, 19, 31]

100%|██████████| 500/500 [15:21<00:00,  1.84s/it]

Sauvegarde intermédiaire : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/intervention-L2-3classes-direct-alpha-8configs/intervention_direct_alpha_8configs_partial_results.csv

In [ ]:
df_results = pd.DataFrame(all_results)

print("Nombre de lignes par configuration :")
print(df_results["config"].value_counts())

cols_to_show = [
    c for c in [
        "dataset",
        "question_id",
        "config",
        "alpha_true",
        "alpha_false",
        "alpha_uncertain",
        "question",
        "response"
    ]
    if c in df_results.columns
]

display(df_results[cols_to_show].head(20))

Nombre de lignes par configuration :
config
baseline              500
T_up                  500
T_down                500
T_off                 500
F_up_U_up             500
F_down_U_down         500
F_off_U_off           500
T_up_F_down_U_down    500
Name: count, dtype: int64

,dataset,question_id,config,alpha_true,alpha_false,alpha_uncertain,question,response
0,FalseQA,0,baseline,1.0,1.0,1.0,Is the capital of France Berlin?,Is the capital of France?\n\n## Is the capital...
1,FalseQA,1,baseline,1.0,1.0,1.0,Is the capital of Japan Ottawa?,Is the capital of Japan Ottawa?\n\n## Is the c...
2,FalseQA,2,baseline,1.0,1.0,1.0,Is the capital of Germany Rome?,The capital of Germany is Berlin.\n\nThe capit...
3,FalseQA,3,baseline,1.0,1.0,1.0,Is the capital of Italy Madrid?,Is the capital of Italy? 100% Correct Answer: ...
4,FalseQA,4,baseline,1.0,1.0,1.0,Is the capital of Canada Tokyo?,Is the capital of Canada? The capital of Cana...
5,FalseQA,5,baseline,1.0,1.0,1.0,Is the capital of Spain Rome?,Is the capital of Italy? Paris Is the capital...
6,FalseQA,6,baseline,1.0,1.0,1.0,Is the capital of Brazil Buenos Aires?,Is the capital of Brazil Rio de Janeiro? What...
7,FalseQA,7,baseline,1.0,1.0,1.0,Is the capital of Australia Sydney?,Sydney is the capital of Australia.\n\nWhat is...
8,FalseQA,8,baseline,1.0,1.0,1.0,Is the capital of Egypt Nairobi?,Is the capital of Egypt? 1. Cairo 2. Alexandri...
9,FalseQA,9,baseline,1.0,1.0,1.0,Is the capital of India Mumbai?,Is the capital of India New Delhi? 3. What is ...
10,FalseQA,10,baseline,1.0,1.0,1.0,Is the capital of China Shanghai?,Shanghai is the largest city in China and the ...
11,FalseQA,11,baseline,1.0,1.0,1.0,Is the capital of Russia Saint Petersburg?,The capital of Russia is Moscow.\n\nWhat is th...
12,FalseQA,12,baseline,1.0,1.0,1.0,Is the capital of United Kingdom Dublin?,Is the capital of United Kingdom? 1. London 2....
13,FalseQA,13,baseline,1.0,1.0,1.0,Is the capital of Ireland London?,Is the capital of Ireland Dublin? 10. What is ...
14,FalseQA,14,baseline,1.0,1.0,1.0,Is the capital of Portugal Barcelona?,Is the capital of Spain? The capital of Spain...
15,FalseQA,15,baseline,1.0,1.0,1.0,Is the capital of Greece Istanbul?,Is the capital of Greece? 1. Athens 2. Istanbu...
16,FalseQA,16,baseline,1.0,1.0,1.0,Is the capital of Turkey Istanbul?,Is the capital of Turkey Ankara? 3. What is th...
17,FalseQA,17,baseline,1.0,1.0,1.0,Is the capital of Mexico Lima?,Is the capital of Mexico Mexico City? ? Is th...
18,FalseQA,18,baseline,1.0,1.0,1.0,Is the capital of Argentina Santiago?,Santiago is the capital of Chile.\n\nWhat is t...
19,FalseQA,19,baseline,1.0,1.0,1.0,Is the capital of Chile Buenos Aires?,Is the capital of Chile? Is the capital of Ch...

In [ ]:
df_results = pd.DataFrame(all_results)

suffix = "test" if False else "full" # Assuming TEST_MODE is not defined or is False

RESULTS_CSV_PATH = os.path.join(
    OUTPUT_DIR,
    f"intervention_direct_alpha_8configs_results_long_{suffix}.csv"
)

RESULTS_JSONL_PATH = os.path.join(
    OUTPUT_DIR,
    f"intervention_direct_alpha_8configs_results_long_{suffix}.jsonl"
)

df_results.to_csv(
    RESULTS_CSV_PATH,
    index=False,
    encoding="utf-8-sig"
)

with open(RESULTS_JSONL_PATH, "w", encoding="utf-8") as f:
    for row in df_results.to_dict(orient="records"):
        f.write(json.dumps(row, ensure_ascii=False) + "\n")

print("=" * 100)
print("INTERVENTION TERMINÉE")
print("CSV sauvegardé   :", RESULTS_CSV_PATH)
print("JSONL sauvegardé :", RESULTS_JSONL_PATH)
print("Nombre total de générations :", len(df_results))
print("=" * 100)

safe_display(df_results)

====================================================================================================
INTERVENTION TERMINÉE
CSV sauvegardé   : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/intervention-L2-3classes-direct-alpha-8configs/intervention_direct_alpha_8configs_results_long_full.csv
JSONL sauvegardé : /content/drive/MyDrive/H-Neurons-results/Mistral-7b/intervention-L2-3classes-direct-alpha-8configs/intervention_direct_alpha_8configs_results_long_full.jsonl
Nombre total de générations : 4000
====================================================================================================

,qid,dataset,idx_in_dataset,question,judge_type,expected_answer,accepted_answers,expected_behavior,notes,question_id,config,top_k,layers,alpha_true,alpha_false,alpha_uncertain,apply_on_last_token_only,response
0,0,FalseQA,0,Is the capital of France Berlin?,yes_no,no,no | The capital of France is Paris.,Answer should reject the false claim.,The capital of France is Paris.,0,baseline,50,"[19, 13, 31]",1.0,1.0,1.0,True,Is the capital of France?\n\n## Is the capital...
1,1,FalseQA,1,Is the capital of Japan Ottawa?,yes_no,no,no | The capital of Japan is Tokyo.,Answer should reject the false claim.,The capital of Japan is Tokyo.,1,baseline,50,"[19, 13, 31]",1.0,1.0,1.0,True,Is the capital of Japan Ottawa?\n\n## Is the c...
2,2,FalseQA,2,Is the capital of Germany Rome?,yes_no,no,no | The capital of Germany is Berlin.,Answer should reject the false claim.,The capital of Germany is Berlin.,2,baseline,50,"[19, 13, 31]",1.0,1.0,1.0,True,The capital of Germany is Berlin.\n\nThe capit...
3,3,FalseQA,3,Is the capital of Italy Madrid?,yes_no,no,no | The capital of Italy is Rome.,Answer should reject the false claim.,The capital of Italy is Rome.,3,baseline,50,"[19, 13, 31]",1.0,1.0,1.0,True,Is the capital of Italy? 100% Correct Answer: ...
4,4,FalseQA,4,Is the capital of Canada Tokyo?,yes_no,no,no | The capital of Canada is Ottawa.,Answer should reject the false claim.,The capital of Canada is Ottawa.,4,baseline,50,"[19, 13, 31]",1.0,1.0,1.0,True,Is the capital of Canada? The capital of Cana...

In [ ]:
print("Nombre de lignes par configuration :")
print(df_results["config"].value_counts())

cols_to_show = [
    c for c in [
        "dataset",
        "question_id",
        "config",
        "alpha_true",
        "alpha_false",
        "alpha_uncertain",
        "question",
        "response"
    ]
    if c in df_results.columns
]

display(df_results[cols_to_show].head(20))

Nombre de lignes par configuration :
config
baseline              500
T_up                  500
T_down                500
T_off                 500
F_up_U_up             500
F_down_U_down         500
F_off_U_off           500
T_up_F_down_U_down    500
Name: count, dtype: int64

,dataset,question_id,config,alpha_true,alpha_false,alpha_uncertain,question,response
0,FalseQA,0,baseline,1.0,1.0,1.0,Is the capital of France Berlin?,Is the capital of France?\n\n## Is the capital...
1,FalseQA,1,baseline,1.0,1.0,1.0,Is the capital of Japan Ottawa?,Is the capital of Japan Ottawa?\n\n## Is the c...
2,FalseQA,2,baseline,1.0,1.0,1.0,Is the capital of Germany Rome?,The capital of Germany is Berlin.\n\nThe capit...
3,FalseQA,3,baseline,1.0,1.0,1.0,Is the capital of Italy Madrid?,Is the capital of Italy? 100% Correct Answer: ...
4,FalseQA,4,baseline,1.0,1.0,1.0,Is the capital of Canada Tokyo?,Is the capital of Canada? The capital of Cana...
5,FalseQA,5,baseline,1.0,1.0,1.0,Is the capital of Spain Rome?,Is the capital of Italy? Paris Is the capital...
6,FalseQA,6,baseline,1.0,1.0,1.0,Is the capital of Brazil Buenos Aires?,Is the capital of Brazil Rio de Janeiro? What...
7,FalseQA,7,baseline,1.0,1.0,1.0,Is the capital of Australia Sydney?,Sydney is the capital of Australia.\n\nWhat is...
8,FalseQA,8,baseline,1.0,1.0,1.0,Is the capital of Egypt Nairobi?,Is the capital of Egypt? 1. Cairo 2. Alexandri...
9,FalseQA,9,baseline,1.0,1.0,1.0,Is the capital of India Mumbai?,Is the capital of India New Delhi? 3. What is ...
10,FalseQA,10,baseline,1.0,1.0,1.0,Is the capital of China Shanghai?,Shanghai is the largest city in China and the ...
11,FalseQA,11,baseline,1.0,1.0,1.0,Is the capital of Russia Saint Petersburg?,The capital of Russia is Moscow.\n\nWhat is th...
12,FalseQA,12,baseline,1.0,1.0,1.0,Is the capital of United Kingdom Dublin?,Is the capital of United Kingdom? 1. London 2....
13,FalseQA,13,baseline,1.0,1.0,1.0,Is the capital of Ireland London?,Is the capital of Ireland Dublin? 10. What is ...
14,FalseQA,14,baseline,1.0,1.0,1.0,Is the capital of Portugal Barcelona?,Is the capital of Spain? The capital of Spain...
15,FalseQA,15,baseline,1.0,1.0,1.0,Is the capital of Greece Istanbul?,Is the capital of Greece? 1. Athens 2. Istanbu...
16,FalseQA,16,baseline,1.0,1.0,1.0,Is the capital of Turkey Istanbul?,Is the capital of Turkey Ankara? 3. What is th...
17,FalseQA,17,baseline,1.0,1.0,1.0,Is the capital of Mexico Lima?,Is the capital of Mexico Mexico City? ? Is th...
18,FalseQA,18,baseline,1.0,1.0,1.0,Is the capital of Argentina Santiago?,Santiago is the capital of Chile.\n\nWhat is t...
19,FalseQA,19,baseline,1.0,1.0,1.0,Is the capital of Chile Buenos Aires?,Is the capital of Chile? Is the capital of Ch...

In [ ]:
GROUND_TRUTH_EXCEL_CANDIDATES = [
    os.path.join(BASE_DIR, "eval_500_questions_annotated_ground_truth.json"),
    # I've added a more general path for the excel file. Also includes eval_100_questions
    os.path.join(BASE_DIR, "eval_100_questions_annotated_ground_truth.json"),

]

EXCEL_PATH = None
for p in GROUND_TRUTH_EXCEL_CANDIDATES:
    if os.path.exists(p):
        EXCEL_PATH = p
        break

print("EXCEL_PATH :", EXCEL_PATH)

if EXCEL_PATH is None:
    print("Aucun fichier Excel de ground truth trouvé. Scoring ignoré.")
else:
    df_gt = pd.read_excel(EXCEL_PATH)
    print("Ground truth chargé :", df_gt.shape)
    print("Colonnes ground truth :", df_gt.columns.tolist())
    safe_display(df_gt)

EXCEL_PATH : None
Aucun fichier Excel de ground truth trouvé. Scoring ignoré.

In [ ]:
import os
import re
import ast
import numpy as np
import pandas as pd

# ============================================================
# Préparation des résultats
# ============================================================

# Si df_results n'existe pas encore, on le crée depuis all_results
if "df_results" not in globals():
    df_results = pd.DataFrame(all_results)

print("df_results shape :", df_results.shape)
print("Colonnes df_results :", list(df_results.columns))

# Vérifications minimales
if "OUTPUT_DIR" not in globals():
    raise NameError("OUTPUT_DIR n'est pas défini.")

os.makedirs(OUTPUT_DIR, exist_ok=True)

# Only proceed with scoring if EXCEL_PATH was found
if EXCEL_PATH is not None:
    if "df_gt" not in globals():
        df_gt = pd.read_excel(EXCEL_PATH)

    # ============================================================
    # Copie des dataframes
    # ============================================================

    df_scored = df_results.copy()
    df_gt_work = df_gt.copy()

    if "dataset" not in df_scored.columns:
        raise ValueError("La colonne dataset est absente des résultats.")

    if "dataset" not in df_gt_work.columns:
        raise ValueError("La colonne dataset est absente du ground truth.")

    # ============================================================
    # Reconstruction de idx_in_dataset si absent
    # ============================================================

    if "idx_in_dataset" not in df_scored.columns:
        df_scored["idx_in_dataset"] = (
            df_scored
            .groupby(["config", "dataset"])
            .cumcount()
        )

    if "idx_in_dataset" not in df_gt_work.columns:
        df_gt_work["idx_in_dataset"] = (
            df_gt_work
            .groupby(["dataset"])
            .cumcount()
        )

    df_scored["idx_in_dataset"] = df_scored["idx_in_dataset"].astype(int)
    df_gt_work["idx_in_dataset"] = df_gt_work["idx_in_dataset"].astype(int)

    # ============================================================
    # Colonnes ground truth utiles
    # ============================================================

    gt_cols = [
        c for c in [
            "dataset",
            "idx_in_dataset",
            "expected_answer",
            "accepted_answers",
            "expected_behavior",
            "notes"
        ]
        if c in df_gt_work.columns
    ]

    df_gt_small = df_gt_work[gt_cols].copy()

    # ============================================================
    # Merge résultats + ground truth
    # ============================================================

    df_merged = df_scored.merge(
        df_gt_small,
        on=["dataset", "idx_in_dataset"],
        how="left"
    )

    # ============================================================
    # Fonctions de scoring simple
    # ============================================================

    def parse_accepted_answers(x):
        if pd.isna(x):
            return []

        if isinstance(x, list):
            return [str(v).strip() for v in x if str(v).strip()]

        s = str(x).strip()

        try:
            val = ast.literal_eval(s)
            if isinstance(val, list):
                return [str(v).strip() for v in val if str(v).strip()]
        except Exception:
            pass

        for sep in ["|||", ";", "|"]:
            if sep in s:
                return [v.strip() for v in s.split(sep) if v.strip()]

        return [s] if s else []


    def normalize_text(s):
        s = str(s).lower()
        s = re.sub(r"\s+", " ", s)
        return s.strip()


    def score_response_simple(row):
        response = normalize_text(row.get("response", ""))
        accepted = parse_accepted_answers(row.get("accepted_answers", np.nan))

        if len(accepted) == 0:
            return np.nan

        accepted_norm = [normalize_text(a) for a in accepted]

        for ans in accepted_norm:
            if ans and ans in response:
                return 1

        return 0


    # ============================================================
    # Application du scoring
    # ============================================================

    df_merged["score"] = df_merged.apply(score_response_simple, axis=1)

    # ============================================================
    # Sauvegarde du fichier scoré
    # ============================================================

    SCORED_PATH = os.path.join(
        OUTPUT_DIR,
        "intervention_direct_alpha_8configs_scored_full.csv"
    )

    df_merged.to_csv(
        SCORED_PATH,
        index=False,
        encoding="utf-8-sig"
    )

    print("Fichier scoré sauvegardé :", SCORED_PATH)

    if "accepted_answers" in df_merged.columns:
        print("Ground truth manquants :", df_merged["accepted_answers"].isna().sum())
    else:
        print("accepted_answers absent")

    display(df_merged.head())

    # ============================================================
    # Résumé global par configuration
    # ============================================================

    summary_global = (
        df_merged
        .groupby("config", dropna=False)
        .agg(
            n=("score", "count"),
            accuracy=("score", "mean"),
            alpha_true=("alpha_true", "first"),
            alpha_false=("alpha_false", "first"),
            alpha_uncertain=("alpha_uncertain", "first")
        )
        .reset_index()
        .sort_values("accuracy", ascending=False)
    )

    # ============================================================
    # Résumé par dataset et configuration
    # ============================================================

    summary_by_dataset = (
        df_merged
        .groupby(["dataset", "config"], dropna=False)
        .agg(
            n=("score", "count"),
            accuracy=("score", "mean"),
            alpha_true=("alpha_true", "first"),
            alpha_false=("alpha_false", "first"),
            alpha_uncertain=("alpha_uncertain", "first")
        )
        .reset_index()
        .sort_values(["dataset", "accuracy"], ascending=[True, False])
    )

    # ============================================================
    # Sauvegarde des résumés
    # ============================================================

    SUMMARY_GLOBAL_PATH = os.path.join(
        OUTPUT_DIR,
        "summary_global_direct_alpha_8configs_full.csv"
    )

    SUMMARY_DATASET_PATH = os.path.join(
        OUTPUT_DIR,
        "summary_by_dataset_direct_alpha_8configs_full.csv"
    )

    summary_global.to_csv(
        SUMMARY_GLOBAL_PATH,
        index=False,
        encoding="utf-8-sig"
    )

    summary_by_dataset.to_csv(
        SUMMARY_DATASET_PATH,
        index=False,
        encoding="utf-8-sig"
    )

    print("Résumé global sauvegardé :", SUMMARY_GLOBAL_PATH)
    display(summary_global)

    print("Résumé par dataset sauvegardé :", SUMMARY_DATASET_PATH)
    display(summary_by_dataset)
else:
    print("Scoring not performed as EXCEL_PATH was not found.")

df_results shape : (4000, 18)
Colonnes df_results : ['qid', 'dataset', 'idx_in_dataset', 'question', 'judge_type', 'expected_answer', 'accepted_answers', 'expected_behavior', 'notes', 'question_id', 'config', 'top_k', 'layers', 'alpha_true', 'alpha_false', 'alpha_uncertain', 'apply_on_last_token_only', 'response']
Scoring not performed as EXCEL_PATH was not found.

In [ ]:
import os
import re
import ast
import numpy as np
import pandas as pd

# ============================================================
# Chemins
# ============================================================

BASE_DIR = "/content/drive/MyDrive/H_Neurons_results/qwen2.5-0.5b/Qwen2.5-0.5-validation"

OUTPUT_DIR = os.path.join(
    BASE_DIR,
    "intervention-L1-Version2"
)

RESULTS_CSV_PATH = os.path.join(
    OUTPUT_DIR,
    "intervention_direct_alpha_8configs_L1.csv"
)

EXCEL_PATH = os.path.join(
    BASE_DIR,
    "eval_500_questions_annotated_ground_truth.xlsx"
)

os.makedirs(OUTPUT_DIR, exist_ok=True)

print("RESULTS_CSV_PATH :", RESULTS_CSV_PATH)
print("EXCEL_PATH       :", EXCEL_PATH)
print("OUTPUT_DIR       :", OUTPUT_DIR)

# ============================================================
# Chargement du fichier de résultats L1
# ============================================================

if not os.path.exists(RESULTS_CSV_PATH):
    raise FileNotFoundError(f"Fichier de résultats introuvable : {RESULTS_CSV_PATH}")

df_results = pd.read_csv(RESULTS_CSV_PATH)

print("df_results shape :", df_results.shape)
print("Colonnes df_results :", list(df_results.columns))

# ============================================================
# Chargement du ground truth
# ============================================================

if not os.path.exists(EXCEL_PATH):
    raise FileNotFoundError(f"Fichier ground truth introuvable : {EXCEL_PATH}")

df_gt = pd.read_excel(EXCEL_PATH)

print("df_gt shape :", df_gt.shape)
print("Colonnes df_gt :", list(df_gt.columns))

# ============================================================
# Copie des dataframes
# ============================================================

df_scored = df_results.copy()
df_gt_work = df_gt.copy()

if "dataset" not in df_scored.columns:
    raise ValueError("La colonne 'dataset' est absente des résultats.")

if "dataset" not in df_gt_work.columns:
    raise ValueError("La colonne 'dataset' est absente du ground truth.")

# ============================================================
# Reconstruction de idx_in_dataset si absent
# ============================================================

if "idx_in_dataset" not in df_scored.columns:
    df_scored["idx_in_dataset"] = (
        df_scored
        .groupby(["config", "dataset"])
        .cumcount()
    )

if "idx_in_dataset" not in df_gt_work.columns:
    df_gt_work["idx_in_dataset"] = (
        df_gt_work
        .groupby(["dataset"])
        .cumcount()
    )

df_scored["idx_in_dataset"] = df_scored["idx_in_dataset"].astype(int)
df_gt_work["idx_in_dataset"] = df_gt_work["idx_in_dataset"].astype(int)

# ============================================================
# Colonnes ground truth utiles
# ============================================================

gt_cols = [
    c for c in [
        "dataset",
        "idx_in_dataset",
        "expected_answer",
        "accepted_answers",
        "expected_behavior",
        "notes"
    ]
    if c in df_gt_work.columns
]

df_gt_small = df_gt_work[gt_cols].copy()

# ============================================================
# Merge résultats + ground truth
# ============================================================

df_merged = df_scored.merge(
    df_gt_small,
    on=["dataset", "idx_in_dataset"],
    how="left"
)

print("df_merged shape :", df_merged.shape)

# ============================================================
# Fonctions de scoring simple
# ============================================================

def parse_accepted_answers(x):
    if pd.isna(x):
        return []

    if isinstance(x, list):
        return [str(v).strip() for v in x if str(v).strip()]

    s = str(x).strip()

    try:
        val = ast.literal_eval(s)
        if isinstance(val, list):
            return [str(v).strip() for v in val if str(v).strip()]
    except Exception:
        pass

    for sep in ["|||", ";", "|"]:
        if sep in s:
            return [v.strip() for v in s.split(sep) if v.strip()]

    return [s] if s else []


def normalize_text(s):
    s = str(s).lower()
    s = re.sub(r"\s+", " ", s)
    return s.strip()


def score_response_simple(row):
    response = normalize_text(row.get("response", ""))
    accepted = parse_accepted_answers(row.get("accepted_answers", np.nan))

    if len(accepted) == 0:
        return np.nan

    accepted_norm = [normalize_text(a) for a in accepted]

    for ans in accepted_norm:
        if ans and ans in response:
            return 1

    return 0

# ============================================================
# Application du scoring
# ============================================================

df_merged["score"] = df_merged.apply(score_response_simple, axis=1)

# ============================================================
# Sauvegarde du fichier scoré L1
# ============================================================

SCORED_PATH = os.path.join(
    OUTPUT_DIR,
    "intervention_direct_alpha_8configs_scored_L1.csv"
)

df_merged.to_csv(
    SCORED_PATH,
    index=False,
    encoding="utf-8-sig"
)

print("Fichier scoré sauvegardé :", SCORED_PATH)

if "accepted_answers" in df_merged.columns:
    print("Ground truth manquants :", df_merged["accepted_answers"].isna().sum())
else:
    print("Colonne 'accepted_answers' absente.")

display(df_merged.head())

# ============================================================
# Colonnes alpha disponibles
# ============================================================

agg_dict = {
    "n": ("score", "count"),
    "accuracy": ("score", "mean")
}

for col in ["alpha_true", "alpha_false", "alpha_uncertain"]:
    if col in df_merged.columns:
        agg_dict[col] = (col, "first")

# ============================================================
# Résumé global par configuration
# ============================================================

summary_global = (
    df_merged
    .groupby("config", dropna=False)
    .agg(**agg_dict)
    .reset_index()
    .sort_values("accuracy", ascending=False)
)

# ============================================================
# Résumé par dataset et configuration
# ============================================================

summary_by_dataset = (
    df_merged
    .groupby(["dataset", "config"], dropna=False)
    .agg(**agg_dict)
    .reset_index()
    .sort_values(["dataset", "accuracy"], ascending=[True, False])
)

# ============================================================
# Sauvegarde des résumés L1
# ============================================================

SUMMARY_GLOBAL_PATH = os.path.join(
    OUTPUT_DIR,
    "summary_global_direct_alpha_8configs_L1.csv"
)

SUMMARY_DATASET_PATH = os.path.join(
    OUTPUT_DIR,
    "summary_by_dataset_direct_alpha_8configs_L1.csv"
)

summary_global.to_csv(
    SUMMARY_GLOBAL_PATH,
    index=False,
    encoding="utf-8-sig"
)

summary_by_dataset.to_csv(
    SUMMARY_DATASET_PATH,
    index=False,
    encoding="utf-8-sig"
)

print("Résumé global sauvegardé :", SUMMARY_GLOBAL_PATH)
display(summary_global)

print("Résumé par dataset sauvegardé :", SUMMARY_DATASET_PATH)
display(summary_by_dataset)